{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
<div id="basebackground" style="background:#f3f3c5;">
	<div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /></div>
    <div id="help"><div class="content" style="background:#f3f3c5;">
        <div id="top" class="headline" style="background:#f39b30;color:#ffffff;text-align:center;">
            <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
          	ﾍﾙﾌﾟ<br />
            <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
        </div><!--/.headline-->
<div class="inner">
		  <div>
          <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
          <div style="font-size:14px;">● ｹﾞｰﾑ操作について ●</div><br />
            <a href="#q1">Q：どうやってお店を開きますか？</a><br />
            <!--<a href="#q2">Q：どうやってお店に入るのですか？ </a><br />-->
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="" /><br />
            <div style="font-size:14px;">● 店内での操作について  ●</div><br />
            <a href="#q4">Q：どうやってﾚﾍﾞﾙｱｯﾌﾟし、Gｺｲﾝ、ｱｲﾃﾑを獲得するのですか？</a><br />
            <a href="#q5">Q：ﾚﾍﾞﾙｱｯﾌﾟした時にもらえる箱は何ですか？</a><br />
            <a href="#q6">Q：どうやってお客さんに提供する道具を買うのですか？</a><br />
            <!--<a href="#q7">Q：どうやってｻｰﾋﾞｽを提供する道具を使うのですか？</a><br />-->
            <a href="#q8">Q：どうやって掃除をするのですか？</a><br />
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div style="font-size:14px;">● ﾏｲﾐｸと一緒にできること ●</div><br />
            <a href="#q9">Q：どうやってﾏｲﾐｸのお店のお客さんを勧誘するのですか？</a><br />
            <a href="#q10">Q：どうやってﾏｲﾐｸのGｺｲﾝ、ｱｲﾃﾑを拾うのですか？</a><br />
            <a href="#q11">Q：どうやってﾏｲﾐｸのお店にｺﾞﾐを捨てるのですか？</a><br />
            <a href="#q13">Q：ｺﾞﾐを捨てたり捨てられたりすると何が起こりますか？</a><br />
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div style="font-size:14px;">● その他 ●</div><br />
            <a href="#q14">Q：どうやってお婆ちゃんから手当てをもらうのですか？</a><br />
            <a href="#q15">Q：どうやって星ﾚﾍﾞﾙを上げるのですか？</a><br />
            <a href="#q16">Q：ﾏｲﾐｸﾘｽﾄのﾗﾝｷﾝｸﾞはどうやって行われますか？</a><br />
			<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            
            <div style="font-size:14px;">● Mｺｲﾝについて ●</div><br />
            <a href="#q17">Q：どうやってMｺｲﾝをﾁｬｰｼﾞするのですか？</a><br />
            <a href="#q18">Q：Mｺｲﾝの利点は何ですか？</a><br />
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div style="font-size:14px;">● 紹介類 ●</div><br />
            <a href="#q19">【 常用類 】</a><br />
            <a href="#q20">【 道具類 】</a><br />
            <a href="#q21">【 ｶｰﾄﾞ類 】（coming soon）</a><br />
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div style="background:#f39b30;text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" /></div>
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
			</div>
            
		  <div class="section">
          	<div id="q1" style="text-decoration:underline; color:#006633">Q：どうやってお店を開きますか？</div><br />
            A：ﾒﾆｭｰの新規出店をｸﾘｯｸすると、空いているﾌﾛｱを探せます。ﾌﾛｱが見つかったら“美容院・ｹｰｷ屋・ｽﾊﾟ”の中から開店したい店ﾀｲﾌﾟを選んでください。<br />
            <!--
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div id="q2" style="text-decoration:underline; color:#006633">Q：どうやってお店に入るのですか？</div><br />
            A：topページの『ﾏｲ店舗へ』ﾘﾝｸをｸﾘｯｸすると自分のお店に入れます。<br />-->
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div style=" text-align:center"><a href="#top">ﾍﾟｰｼﾞﾄｯﾌﾟへ</a></div>
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div style="background:#f39b30;text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" /></div>
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
          </div><!--/.section-->
          
          
          	<div class="section">
            <div id="q4" style="text-decoration:underline; color:#006633">Q：どうやってﾚﾍﾞﾙｱｯﾌﾟし、Gｺｲﾝ、ｱｲﾃﾑを獲得するのですか？</div><br />
            A：ﾒﾆｭｰの接客から、待合室で待っているお客様をお店の椅子に案内し、ｻｰﾋﾞｽを提供します。作業終了時に経験値、Gｺｲﾝ、ｱｲﾃﾑを獲得できます。<br />
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div id="q5" style="text-decoration:underline; color:#006633">Q：ﾚﾍﾞﾙｱｯﾌﾟした時にもらえる箱は何ですか？</div><br />
            A：開封すると色々な便利ｱｲﾃﾑをｹﾞｯﾄできます。<br />
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div id="q6" style="text-decoration:underline; color:#006633">Q：どうやってお客さんに提供する道具を買うのですか？</div><br />
            A：1.お客さんを店内の椅子に案内した後、道具がない場合ｱｲﾃﾑをそろえるというﾘﾝｸが表示されますので、ｸﾘｯｸすると購入する画面に移動します。<br /> 
            &nbsp;2.ﾒﾆｭｰのｼｮｯﾌﾟをｸﾘｯｸして、ｼｮｯﾌﾟでｱｲﾃﾑを買います。<br />
            <!--
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div id="q7" style="text-decoration:underline; color:#006633">Q：どうやってｻｰﾋﾞｽを提供する道具を使うのですか？</div><br />
            A：業務ﾒﾆｭｰの注文をｸﾘｯｸすると、注文待ちのお客様の一覧がでます。注文をきくをｸﾘｯｸすると注文を受け付け、作業が開始されます。<br />-->
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div id="q8" style="text-decoration:underline; color:#006633">Q：どうやって掃除をするのですか？</div><br />
            A：店舗にｺﾞﾐがある場合は、ﾒﾆｭｰに掃除のﾘﾝｸが表示されます。ﾘﾝｸをｸﾘｯｸし、ｺﾞﾐのある席をｸﾘｯｸしたら掃除ができます。ただし、ｺﾞﾐが複数置いてある場合は、一回の掃除ではｺﾞﾐが全部なくなりません。その場合は、ｺﾞﾐが置いてある個数分掃除をする必要があります。<br /> 
            (１つのｺﾞﾐ掃除につき２Ｇ入手) <br />
            　(ﾏｲﾐｸの店での掃除は自分で落としたｺﾞﾐ以外なら掃除可能)<br />
			<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div style=" text-align:center"><a href="#top">ﾍﾟｰｼﾞﾄｯﾌﾟへ</a></div>
          <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div style="background:#f39b30;text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" /></div>
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
          </div><!--/.section-->
          
        <div class="section"> 
        <div id="q9" style="text-decoration:underline; color:#006633">Q：どうやってﾏｲﾐｸのお店のお客さんを勧誘するのですか？</div><br />
        A：ﾒﾆｭｰの接客をｸﾘｯｸすると、｢ﾏｲﾐｸのお店から勧誘する｣というﾘﾝｸが表示されます。同じﾀｲﾌﾟのお店を開業しているﾏｲﾐｸの一覧が表示され、そのお店をｸﾘｯｸすると、そのお店の待合室に移動します。勧誘可能なお客様の場合、勧誘するがｸﾘｯｸできるようになっています。<br />
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
        <div id="q10" style="text-decoration:underline; color:#006633">Q：どうやってﾏｲﾐｸのGｺｲﾝ、ｱｲﾃﾑを拾うのですか？</div><br />
        A：ﾏｲﾐｸのお店へ行き、ﾒﾆｭｰの集金をｸﾘｯｸすると、ｺｲﾝやｱｲﾃﾑをｹﾞｯﾄできます。<br /> 
        ※ﾏｲﾐｸのお店に限ります。<br />
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
        <div id="q11" style="text-decoration:underline; color:#006633">Q：どうやってﾏｲﾐｸのお店にｺﾞﾐを捨てるのですか？</div><br />
        A：ﾏｲﾐｸのお店へ行って、ﾒﾆｭｰのｺﾞﾐをｸﾘｯｸしたらｺﾞﾐが捨てられます。 <br />
        ※制限は1日５０個です。<br />
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
        <div id="q13" style="text-decoration:underline; color:#006633">Q：ｺﾞﾐを捨てたり捨てられたりすると何が起こりますか？</div><br />
        A：ｺﾞﾐを捨てた側は、何も起こりません。 <br />
        (経験値･お金の収得はなし) <br />
        ｺﾞﾐを捨てられた側は、「掃除」をする事で、１つのｺﾞﾐにつき２Gが手に入ります。 <br />
        (経験値の取得はなし。)<br />
        
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div style=" text-align:center"><a href="#top">ﾍﾟｰｼﾞﾄｯﾌﾟへ</a></div>
          <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div style="background:#f39b30;text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" /></div>
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
          </div><!--/.section-->
          
         <div class="section">  
        <div id="q14" style="text-decoration:underline; color:#006633">Q：どうやってお婆ちゃんから手当てをもらうのですか？</div><br />
        A：ﾏｲﾍﾟｰｼﾞの店舗画像の上に、お婆ちゃんからのﾎﾞｰﾅｽがある場合は、ﾘﾝｸが表示されます。ﾘﾝｸをｸﾘｯｸすると、問題と回答画面が出てきます。<br /> 
        選んだ回答によってもらえるGｺｲﾝが異なります。<br />
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
        <div id="q15" style="text-decoration:underline; color:#006633">Q：どうやって星ﾚﾍﾞﾙを上げるのですか？</div><br />
        A：お店のﾚﾍﾞﾙ10毎に星ﾚﾍﾞﾙを一つ上げることが可能です。その際Gｺｲﾝも必要となります。<br />
        ﾏｲ店舗の星の画像横の『ﾗﾝｸｱｯﾌﾟ』をｸﾘｯｸするとお店ﾚﾍﾞﾙを上げる画面に移動します。<br />
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
        <div id="q16" style="text-decoration:underline; color:#006633">Q：ﾏｲﾐｸﾘｽﾄのﾗﾝｷﾝｸﾞはどうやって行われますか？</div><br />
        A：ﾏｲﾐｸﾘｽﾄのﾗﾝｷﾝｸﾞはﾕｰｻﾞｰﾚﾍﾞﾙによってﾗﾝｷﾝｸﾞされます。<br />
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div style=" text-align:center"><a href="#top">ﾍﾟｰｼﾞﾄｯﾌﾟへ</a></div>
          <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div style="background:#f39b30;text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" /></div>
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
          </div><!--/.section-->  
          
          
          <div class="section"> 
            <div id="q17" style="text-decoration:underline; color:#006633">Q：どうやってMｺｲﾝをﾁｬｰｼﾞするのですか？</div><br />
            A：Mｺｲﾝﾁｬｰｼﾞ機能は現在まだ使えません。MixiのPC版Happy Towerから購入可能です。携帯版も対応予定ですのでしばらくお待ちください。<br />
			<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div id="q18" style="text-decoration:underline; color:#006633">Q：Mｺｲﾝの利点は何ですか？</div><br />
            A：Mｺｲﾝを利用してﾑｰﾄﾞ道具・加速道具・ｶｰﾄﾞ・花ﾊﾞｽｹｯﾄといった ﾚﾍﾞﾙｱｯﾌﾟに便利な道具を購入できます。<br />
			<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div style=" text-align:center"><a href="#top">ﾍﾟｰｼﾞﾄｯﾌﾟへ</a></div>
          <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div style="background:#f39b30;text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" /></div>
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
          </div><!--/.section--> 
          
          <div class="section"> 
          <div id="q19" style="text-decoration:underline; color:#006633">【 常用類 】</div><br />
            お客さんにｻｰﾋﾞｽを提供するために使う道具のことです。<br />
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div id="q20" style="text-decoration:underline; color:#006633">【 道具類 】</div><br />
            <strong>ﾑｰﾄﾞ道具：</strong>お客さんのﾑｰﾄﾞを増加することによって得る経験も増加します。<br /> 
            ﾏｲﾐｸのために使う道具もあります。 <br />
            ※お客さんのﾑｰﾄﾞが100になるまで何度でも使用可能です。<br />
            <strong>加速道具：</strong>作業の時間を短縮するために使う道具です。 <br />
            ﾏｲﾐｸのために使う道具もあります。 <br />
            ※1人のお客さんにつき1回しか使用できません。<br />
            <strong>花ﾊﾞｽｹｯﾄ：</strong>毎日いつでも１０人のお客さんを招待できます。 <br />
            ※有効時間は７２時間です。<br />
			<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div id="q21" style="text-decoration:underline; color:#006633">【 ｶｰﾄﾞ類 】（coming soon）</div><br />
            <strong>引越しｶｰﾄﾞ：</strong>自分のお店を本来の状態のまま、他の空いているﾌﾛｱに引越しします。<br />
            <strong>ﾘｾｯﾄｶｰﾄﾞ：</strong>自分のお店ﾀｲﾌﾟを変えるために使うものです。 <br />
            使う際、元のお店のﾃﾞｰﾀはすべてﾘｾｯﾄされます。 <br />
            ※一つ星、０級からの再ｽﾀｰﾄとなります。<br />
            <strong>自爆ｶｰﾄﾞ：</strong>自分のお店に関するすべてのﾃﾞｰﾀを削除し、賃貸する時に使用した１５０００ｺｲﾝをﾕｰｻﾞｰに返却します。<br />
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />
            <div style=" text-align:center"><a href="#top">ﾍﾟｰｼﾞﾄｯﾌﾟへ</a></div>
          </div><!--/.section--> 
          
	  </div>
        <!--/.inner-->
    <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
			</div><!--/.content-->
    </div>  <!--/#help-->
    </div>
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" style="margin-bottom:5px;" /><br />

{%include file="common/common.phtml"%}
</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
