{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
	<div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
	<div id="basebackground" style="background:#f3f3c5;">
		<div id="shop">
			<div class="content" style="background:#f3f3c5;">
			  <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
				  <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				  ｱｲﾃﾑ<br />
				  <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			  </div><!--/.headline-->
            </div><!--/.content-->
            <table><tr><td></td></tr></table>
            <div class="content" style="text-align:center">
                                <div style="text-align:left;font-size:x-small;width:240px;">
                                        <img src="{%$staticUrl%}/apps/tower/mobile/img/item/55.gif" style="float:left;margin-right:10px" align="left" />
                                        宝箱やお客様が置いていったｱｲﾃﾑはここから確認！<br />
                                        <a href='{% "$baseUrl/mobile/toweritem/itembox?CF_type=3"|mixiurl %}'>確認する</a>
                                </div>
                                <div style="text-align:center;clear:both;" clear="all">
				<img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" style="margin:10px 0px;" />
                                </div>
                                <div style="text-align:left;font-size:x-small;width:240px;">
                                        <img src="{%$staticUrl%}/apps/tower/mobile/img/item/1.gif" style="float:left;margin-right:10px" align="left" />
                                        いつも使うアイテムはココから残りの数を確認しよう！<br />
                                        <a href='{% "$baseUrl/mobile/toweritem/itembox?CF_type=2"|mixiurl %}'>確認する</a>

                                </div>
                                <div style="text-align:center;clear:both;" clear="all">
				<img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" style="margin:10px 0px;" />
                                </div>
                                <div style="text-align:left;font-size:x-small;width:240px;">
                                        <img src="{%$staticUrl%}/apps/tower/mobile/img/item/17.gif" style="float:left;margin-right:10px" align="left" />
                                        加速ｼﾞｭｰｽやﾑｰﾄﾞUPｱｲﾃﾑは持っているかな？<br />
                                        <a href='{% "$baseUrl/mobile/toweritem/itembox?CF_type=1"|mixiurl %}'>確認する</a>

                                </div>
                                <div style="text-align:center;clear:both;" clear="all">
				<img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" style="margin:10px 0px;" />
                                </div>
                                <div style="text-align:left;font-size:x-small;width:240px;">
                                        <img src="{%$staticUrl%}/apps/tower/mobile/img/item/2001.gif" style="float:left;margin-right:10px" align="left" />
                                        もらったﾌﾟﾚｾﾞﾝﾄを確認してみよう！<br />
                                        <a href='{% "$baseUrl/mobile/towerpresent/presenthistory?CF_read=1"|mixiurl %}'>確認する</a>

                                </div>
                                <div style="text-align:center;clear:both;" clear="all">
				<img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" style="margin:10px 0px;" />
             </div>
         </div>
		</div>
        <div style="text-align:center"><img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" /></div>
	</div><!--/#basebackground -->
	{%include file="common/common.phtml"%}
</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}