{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
<div id="basebackground" style="background:#f3f3c5;">
	<div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="itembox">
          <div class="content" style="background:#f3f3c5;">
              <div class="headline" style="background:#c17f58;color:#ffffff;text-align:center;">
                  <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                  ﾏｲｱｲﾃﾑ箱<br />
                  <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
              </div><!--/.headline-->
              <div class="classification" style="text-align:center;font-size:x-small;">
           [{%if $type==1%}道具{%else%}<a href='{% "$baseUrl/mobile/toweritem/itembox?CF_type=1"|mixiurl %}'>道具</a>{%/if%}|{%if $type==2%}常用{%else%}<a href='{% "$baseUrl/mobile/toweritem/itembox?CF_type=2"|mixiurl %}'>常用</a>{%/if%}|{%if $type==3%}その他{%else%}<a href='{% "$baseUrl/mobile/toweritem/itembox?CF_type=3"|mixiurl %}'>その他</a>{%/if%}|{%if $type==4%}飾り{%else%}<a href='{% "$baseUrl/mobile/toweritem/itembox?CF_type=4"|mixiurl %}'>飾り</a>{%/if%}]</div>
              <div class="inner">
              {%foreach from=$itemList item=data%}
                  <div class="section">
                    <table width="100%" cellpadding="0" cellspacing="0" border="0">
                      <tr>
                        <td valign="top" style="width:55px;text-align:center; vertical-align:top;"><img src="{%$staticUrl%}/apps/tower/mobile/img/item/{%$data.id%}.gif" width="50" height="50" style="margin:3px 0;" /></td>
                        <td style="font-size:x-small;">
                            <div style="font-size:x-small;"><span style="font-size:x-small; color:#0d3a89">{%$data.name%}</span><br />
                                                                保有数：<span style="color:#0d3a89">{%$data.num%}</span>&nbsp;個<br />
                                                                売却額：<img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/{%if $data.is_sell==1%}goldicon_17x17.gif{%else%}micon_17x17.gif{%/if%}" width="17" height="17" align="top" />{%$data.sellPrice%}<br />
                                {%if $data.can_open==1%}
                                    <a href='{% "$baseUrl/mobile/toweritem/opengiftconfirm?CF_gid=`$data.id`"|mixiurl %}'>ｵｰﾌﾟﾝ</a>&nbsp;&nbsp;&nbsp;
                                {%/if%}
                                <!--
                                {%if $data.id==30 || $data.id==31 || $data.id==32%}
                                    <a href='{% "$baseUrl/mobile/tower/useitem?CF_itemid=`$data.id`"|mixiurl %}'>使用</a>&nbsp;&nbsp;&nbsp;
                                {%/if%}
                                -->
                                {%if $data.is_sell==1%}
                                    <a href='{% "$baseUrl/mobile/toweritem/sellitem?CF_itemId=`$data.id`&CF_itemCount=`$data.num`&CF_type=$type"|mixiurl %}'>売る</a>
                                {%else%}<span style="color:#666666">売る</span>
                                {%/if%}

                            </div>
                        </td>
                      </tr>
                    </table>
                      <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                      <div style="background:#c17f58;text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" /></div>
                      <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                  </div><!--/.section-->

                  {% /foreach %}
                <div class="page" style="text-align: center;">
                    {%include file="common/pager.phtml"%}<br />
                </div>
               <div style="text-align: left;">
               	便利なｱｲﾃﾑをｼｮｯﾌﾟで購入しよう<br />
                        <blink><a href='{% "$baseUrl/mobile/towershop/shop"|mixiurl %}' style="font-size:13px">ｼｮｯﾌﾟへ</a></blink>≪
                    </div>
              </div><!--/.inner-->
              <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
			</div><!--/.content-->
        <!--/#landlord-->
</div>
        </div>
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
        {%include file="common/common.phtml"%}

</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
