{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
		<div id="basebackground" style="background:#f3f3c5;">
        <div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="complete">
            <div class="content" style="background:#f3f3c5;">
                <div class="headline" style="background:#c17f58;color:#ffffff;text-align:center;">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                    宝箱ｵｰﾌﾟﾝ<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                </div><!--/.headline-->
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align: left;">宝箱ｵｰﾌﾟﾝし、<br />
                ｱｲﾃﾑを手に入れました。</div>
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />

                <div>
                  {% foreach from=$giftList item=data%}
                  <table width="100%" cellpadding="0" cellspacing="0" border="0">
                    <tr>
                      <td valign="top" style="width:68px;text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/item/{%$data.id%}.gif" style="margin:3px 0;" /></td>
                      <td><div style="font-size:x-small; padding-left:10px; line-height:18px; text-align:left"><span style="color:#0d3a89; font-size:x-small;">{%$data.name%}</span><br />
                          数量：{%$data.nm%}<br />
                        <span style="font-size:x-small;">{%$data.des%}</span></div></td>
                    </tr>
                  </table>
                  <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                      <div style="background:#c17f58;text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" /></div>
                      <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                  {%/foreach %}
                  </div>
                    <div style="text-align:center;">
                        ≫<a href='{% "$baseUrl/mobile/toweritem/itembox"|mixiurl %}'>ｱｲﾃﾑ箱へ戻る</a>≪
                    </div>
                </div><!--/.inner-->
                <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
			</div><!--/.content-->
        </div><!--/#complete-->
        </div>
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />

{%include file="common/common.phtml"%}
</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
