{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
		<div id="basebackground" style="background:#f3f3c5;">
        <div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        {%if $step=="start"%}
        <div id="debut">
            <div class="content" style="background:#f3f3c5;">
                <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                    ﾌﾛｱの賃貸<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                </div><!--/.headline-->
                <div class="inner">
                <form method="post" action='{% "$baseUrl/mobile/tower/afterselectnewfloor"|mixiurl %}'>
                    <input type="hidden" name="CF_step" value="confirm">
                    <input type="hidden" name="CF_floorid" value="{%$fid%}">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
					第{%$fid%}ﾌﾛｱを借りて開店しますか<br />
                                        開店条件：<br />
               &nbsp;{%if $storeCount==3%}<img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/batsu.gif" width="15" height="15" align="top" />
                    <span style="color:#f5102b">{%else%}<img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/maru.gif" width="15" height="15" align="top" /><span style="color:#0c6902">{%/if%}不動産上限：3店</span><br />
                    {%if $storeCount<3%}
                 &nbsp;{%if $gb<15000%}<img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/batsu.gif" width="15" height="15" align="top" /><span style="color:#f5102b">{%else%}<img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/maru.gif" width="15" height="15" align="top" /><span style="color:#0c6902">{%/if%}必要：<img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/goldicon_17x17.gif" width="17" height="17" align="top" />15000</span><br />
               &nbsp;{%if $level<$needLevel%}<img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/batsu.gif" width="15" height="15" align="top" /><span style="color:#f5102b">{%else%}<img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/maru.gif" width="15" height="15" align="top" /><span style="color:#0c6902">{%/if%}Lv{%$needLevel%}</span>
                    {%/if%}
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />

                    <table border="0" align="center" cellpadding="0" cellspacing="0" style="background:#f3f3c5;">
                    <tr>
                      <td colspan="3" style="text-align:left; background:#FF9900; font-size:x-small;"><div style="font-size:x-small;">お店のﾀｲﾌﾟを選択してください</div></td>
                      </tr>
                    <tr>
                        <td width="80" align="center" style="font-size:x-small;"><div style="font-size:x-small;"><input name="store_type" type="radio" id="RadioGroup1_0" value="1" {%if $storeType==1%}checked="checked"{%/if%} />美容院</div></td>
                        <td width="80" align="center" style="font-size:x-small;"><div style="font-size:x-small;"><input name="store_type" type="radio" id="RadioGroup1_2" value="2" {%if $storeType==2%}checked="checked"{%/if%}/>ｹｰｷ屋</div></td>
                        <td width="80" align="center" style="font-size:x-small;"><div style="font-size:x-small;"><input name="store_type" type="radio" id="RadioGroup1_3" value="3" {%if $storeType==3%}checked="checked"{%/if%}/>ｽﾊﾟ</div></td>
                    </tr>
                     <tr>
                    <td align="center"><img src="{%$staticUrl%}/apps/tower/mobile/img/icon/60x60_01.gif" width="60" height="60"   /></td>
                    <td align="center"><img src="{%$staticUrl%}/apps/tower/mobile/img/icon/60x60_02.gif" width="60" height="60"   /></td>
                    <td align="center"><img src="{%$staticUrl%}/apps/tower/mobile/img/icon/60x60_03.gif" width="60" height="60"   /></td>
                     </tr>
                     <tr>
                       <td colspan="3" align="center" style="font-size:x-small;">
                       <div style="font-size:x-small; text-align:center;">
                       {%if $emoj%}<span style="color:#f5102b;">店名には絵文字が使えません</span><br />{%/if%}
                         <input name="CF_storeName" type="text" {%if $storeName%}value="{%$storeName%}"{%else%}value="お店の名前を入力"{%/if%} size="30" maxlength="9"/><br />
							<span style="color:#f5102b;">※9文字以内</span>

                       </div></td>
                      </tr>
                     <tr>
                       <td colspan="3" align="center">
                       {%if $canOpen%}
                        <div style="text-align:center;font-size:x-small;">
                            <input type="submit" value="確認" style="color:#000;font-size:x-small;" />
                        </div>
                        {%/if%}
                       </td>
                     </tr>
                    </table>
                </form>
                {%if $canOpen%}
                <form action='{% "$baseUrl/mobile/tower/opennewstore"|mixiurl %}' style="text-align:center">
                    <input type="submit" value="戻る" style="color:#000;font-size:x-small;" />
                </form>
                {%else%}
                <form action='{% "$baseUrl/mobile/tower/home"|mixiurl %}' style="text-align:center">
                    <input type="submit" value="戻る" style="color:#000;font-size:x-small;" />
                </form>
                {%/if%}

                <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                            <div style="color:#F00; text-align:center">このｱﾌﾟﾘは性別を公開する仕組みになっております。</div>
                </div><!--/.inner-->
            <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
			</div><!--/.content-->
        </div><!--/#debut-->
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
        {%/if%}

        {%if $step=="confirm"%}
            <div id="debut">
                <div class="content" style="background:#f3f3c5;">
                    <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                                                        ﾌﾛｱの賃貸<br />
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                    </div><!--/.headline-->
                    <div class="inner">
                    <form method="post" action='{% "$baseUrl/mobile/tower/afterselectnewfloor"|mixiurl %}'>
                        <input type="hidden" name="CF_step" value="complete">
                        <input type="hidden" name="CF_floorid" value="{%$fid%}">
                        <input type="hidden" name="CF_storeName" value="{%$storeName%}">
                        <input type="hidden" name="CF_storeType" value="{%$storeType%}">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                                                                    第{%$fid%}階を借ります。<br />
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                                                            お店ﾀｲﾌﾟ：{%$sysStoreName%}<br />
                                                            お店の名前：{%$storeName%}<br /><br /><br />
                        <div style="color:#f5102b;text-align:center;">※この内容でよろしいですか？</div>
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                        <div style="text-align:center;">
                            <input type="submit" value="確認" style="color:#000;font-size:x-small;" />
                        </div>
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                    </form>
                    <form action='{% "$baseUrl/mobile/tower/afterselectnewfloor"|mixiurl %}' method="post">
                        <div style=" text-align:center">
                            <input type="hidden" name="CF_floorid" value="{%$fid%}">
                            <input type="hidden" name="CF_error" value="1">
                            <input type="hidden" name="CF_storeName" value="{%$storeName%}">
                            <input type="hidden" name="CF_storeType" value="{%$storeType%}">
                            <input type="submit" value="やめる" style="color:#000;font-size:x-small;" />
                        </div>
                    </form>
                    </div><!--/.inner--><img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" /></div>
                </div><!--/.content--><!--/#debut-->
        {%/if%}
        {%if $step=="complete"%}
            {%if $isRepeat%}
                <div id="debut">
                    <div class="content" style="background:#f3f3c5;">
                        <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                            <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                                                ﾌﾛｱの賃貸<br />
                            <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                        </div><!--/.headline-->
                        <div class="inner">
                            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                                                    第{%$fid%}階は埋まってしまいました。<br />
                                                     別の第{%$newFloorId%}階でｽﾀｰﾄしてよろしいですか？
                            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                            <div style="text-align:center;">
                                <table border="0" cellspacing="5" cellpadding="0">
                                    <tr>
                                        <td>
                                            <form action='{% "$baseUrl/mobile/tower/afterselectnewfloor"|mixiurl %}' method="post">
                                                <input type="hidden" name="CF_floorid" value="{%$newFloorId%}">
                                                <input type="hidden" name="CF_storeName" value="{%$storeName%}">
                                                <input type="hidden" name="CF_storeType" value="{%$storeType%}">
                                                <input type="hidden" name="CF_step" value="complete">
                                                <input type="submit" value="はい">
                                            </form>
                                        </td>
                                        <td>
                                            <form action='{% "$baseUrl/mobile/tower/opennewstore"|mixiurl %}' method="post">
                                                <input type="submit" value="戻る">
                                            </form>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div><!--/.inner-->
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
		</div><!--/.content-->
                </div><!--/#debut-->
            {%else%}
                <div id="complete">
                    <div class="content" style="background:#f3f3c5;">
                        <div class="inner">
                            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                            <div class="img" style="text-align:center;"><span class="img" style="text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/character/v1/landlord_happy.jpg"   /></span></div>
                            <div style="text-align:center;">開店成功！</div>
                            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                            <div style="text-align:center;">
                                                            ≫<a href='{% "$baseUrl/mobile/tower/home?CF_floorid=`$floorId`"|mixiurl %}'>ﾏｲ店舗へ</a>≪
                            </div>

                        </div><!--/.inner-->
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
					</div><!--/.content-->
                </div><!--/#complete-->
                {%/if%}
                </div><!--/#basebackground-->
       {%/if%}
       </div><!--/#container-->
	{%include file="common/common.phtml"%}
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}