{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
	<div id="basebackground" style="background:#f3f3c5;">
	<div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
	{% if $step=="start" %}
	<div id="confirm">
		<div class="content" style="background:#f3f3c5;">
			<div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				招待<br />
				<img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			</div><!--/.headline-->

			<div class="inner">
				<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
				<div style="text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/character/v1/{%$guestInfo.id%}.gif" width="64" height="79" /><br />{%$guestInfo.name|escape%}を招待しますか？</div>
				<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
				<div style="text-align:center;">
					<a href='{% "$baseUrl/mobile/tower/basketinviteconfirm?CF_floorid=`$floorId`&CF_gid=`$guestInfo.id`&CF_step=complete"|mixiurl %}'>招待する</a>&nbsp;&nbsp;<a href='{% "$baseUrl/mobile/tower/basketinvite?CF_floorid=`$floorId`"|mixiurl %}'>やめる</a>
				</div>
			</div><!--/.inner-->
			<img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
		</div><!--/.content-->
	</div><!--/#confirm-->

	{% elseif $step=="complete" %}
	<div id="complete">
		<div class="content" style="background:#f3f3c5;">
			<div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				招待確認<br />
				<img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			</div><!--/.headline-->

			<div class="inner">
				<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                                <div style="text-align:center;">
                                <object data="{%$staticUrl%}/apps/tower/mobile/swf/character/{%$guestInfo.id%}.swf" type="application/x-shockwave-flash" width="100"   height="110">
                                <param name="bgcolor" value="#f3f3c5">
                                <param name="loop" value="off">
                                <param name="quality" value="high">
                                <!--<embed src="{%$staticUrl%}/apps/tower/mobile/swf/character/{%$guestInfo.id%}.swf" width="100" height="110" loop="on" quality="high"   bgcolor="#000000"></embed>-->
                                </object><!--
				<img src="{%$staticUrl%}/apps/tower/mobile/img/character/v1/{%$guestInfo.id%}.gif" width="64" height="79" />-->
                                </div>
				<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
				<div style="text-align:center;">{%$guestInfo.name|escape%}を招待しました</div>
				<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
				<div style="text-align:center;">
					{%*≫<a href='{% "$baseUrl/mobile/towerservice/waitingroom?CF_floorid=`$floorId`"|mixiurl %}'>さっそく、座席に案内する</a>*%}
                    <a href='{% "$baseUrl/mobile/towerservice/guideseat?CF_floorid=`$floorId`&CF_ha=`$guestInfo.ha`&CF_chairid=`$guestInfo.chair_id`&CF_guestid=`$guestInfo.id`"|mixiurl %}' accesskey="5" style="font-size:medium">{%emoji code="F98B"%}お客様を接客する</a><br />
                    <a href='{% "$baseUrl/mobile/tower/basketinvite?CF_floorid=`$floorId`"|mixiurl %}'>≫もっと招待する≪</a><br />
				</div>
			</div><!--/.inner-->
            <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
		</div><!--/.content-->
	</div><!--/#complete-->
	{% /if %}
    </div><!--/#basebackground-->
	<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
	{%include file="common/common.phtml"%}
</div><!--/#container-->

{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}