{%include file="header.phtml"%}
h{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
	<div id="basebackground" style="background:#f3f3c5;">
	<div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
	{% if $step=="start" %}
	<div id="changemood">
            <div class="content" style="background:#f3f3c5;">
                <div class="headline" style="background:#a70f0f;color:#ffffff;text-align:center;">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                    編集<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                </div><!--/.headline-->
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
ﾑｰﾄﾞを入力してください
                    <form method="post" action='{% "$baseUrl/mobile/tower/editname"|mixiurl %}' style="text-align:center;">
                      <input type="hidden" name="CF_floorid" value="{%$floorId%}" />
                        <input type="hidden" name="CF_step" value="complete" />
                        <input type="hidden" name="CF_edittype" value="storeSign" />
                        <div style="text-align:center">
                          <input name="txtSign" type="text" {%if $editType=='storeSign'%}value="{%$storeInfo.sign%}"{%else%}value="{%$storeInfo1.sign%}"{%/if%} maxlength=20/>
                        </div>
                        {%if $signEmoj%}<span style="color:#f5102b;">絵文字が使えません</span><br />{%/if%}
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="1" /><br />
                        <div class="btn" style="text-align:center"><input name="" type="submit" value="変 更"/>
                    </form>
                    <form method="post" action='{% "$baseUrl/mobile/tower/home"|mixiurl %}' style="text-align:center;">
                        <input type="hidden" name="CF_floorid" value="{%$floorId%}" />
                      <input name="cancel2" type="submit" value="やめる"/>
                    </form>
                     <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                </div><!--/.inner-->

                <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
お店の名を入力してください
                    <form method="post" action='{% "$baseUrl/mobile/tower/editname"|mixiurl %}' style="text-align:center;">
                      <input type="hidden" name="CF_floorid" value="{%$floorId%}" />
                        <input type="hidden" name="CF_step" value="complete" />
                        <input type="hidden" name="CF_edittype" value="storeName" />
                        <div style="text-align:center">
                        <input name="txtName" type="text" {%if $editType=='storeSign'%}value="{%$storeInfo.name%}"{%else%}value="{%$storeInfo1.name%}"{%/if%} maxlength=9/><br />
                            <div style="color:#f5102b;text-align:center;">※9文字以内</div>
                        </div>
                        {%if $nameEmoj%}<span style="color:#f5102b;">絵文字が使えません</span><br />{%/if%}
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="1" /><br />
                        <div class="btn" style="text-align:center"><input name="" type="submit" value="変 更"/>
                    </form>
                    <form action='{% "$baseUrl/mobile/tower/home"|mixiurl %}' method="post" style="text-align:center;">
                        <input type="hidden" name="CF_floorid" value="{%$floorId%}" />
                        <input name="cancel" type="submit" value="やめる"/>
                    </form>
                     <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                </div>
			<img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
            </div><!--/.content-->
    </div><!--/#changename-->

    {% elseif $step=="complete" %}
	<div id="confrim">
		<div class="content" style="background:#f3f3c5;">
			<div class="headline" style="background:#a70f0f;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				{%if $editType=='storeName'%}店名の変更{%elseif $editType=='storeSign'%}ﾑｰﾄﾞを変更{%/if%}<br />
				<img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			</div><!--/.headline-->

			<div class="inner">
				<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
				<div style="text-align:center;">{%if $editType=='storeName'%}店名を変更しました{%elseif $editType=='storeSign'%}ﾑｰﾄﾞを変更しました{%/if%}</div>
				<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
				<div style="text-align:center;">
					≫<a href='{% "$baseUrl/mobile/tower/home"|mixiurl %}'>ﾏｲ店舗へ戻る</a>≪
				</div>
			</div><!--/.inner-->
           <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
		</div><!--/.content-->
        </div><!--/#basebackground-->
	</div><!--/#confirm-->
	{% /if %}
</div><!--/#container-->
{%include file="common/common.phtml"%}
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}