{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small">
	<div id="info" style="font-size:x-small;background:#f3f3c5;">
        <div id="header">
        <div class="headline" style="background:#a70f0f;color:#ffffff;text-align:center;">
        	<img src="{%$staticUrl%}/apps/tower/mobile/img/line.gifw.gif" width="100%" height="1" style="margin:1px 0;" /><br />
        	運営からのお知らせ<br />
        	<img src="{%$staticUrl%}/apps/tower/mobile/img/line.gifw.gif" width="100%" height="1" style="margin:1px 0;" /><br />
        </div><!--/.headline-->
        </div><!--/#header-->
                        <div class="content">
                                <div style="text-align:left;color:#F00">
                                        ｻｰﾊﾞｰﾒﾝﾃﾅﾝｽのお知らせ
                                </div>
                                <div style="text-align:left;">
                                        いつもﾊｯﾋﾟｰﾀﾜｰﾓﾊﾞｲﾙをご利用頂き、誠に有難うございます。<br />
                                        ｻｰﾊﾞｰﾒﾝﾃﾅﾝｽの為、ｱﾌﾟﾘをご利用になることが出来なくなります。<br /><br />

                                        期間:<br />2010年6月7日23時～6月8日6時<br /><br />

                                        ｻｰﾊﾞｰﾒﾝﾃﾅﾝｽ中はﾛｸﾞｲﾝ等出来なくなりますので、<br />
                                        ﾒﾝﾃﾅﾝｽ時間前にはﾛｸﾞｱｳﾄをお願い致します。<br />
                                        お客様にはご不便をおかけしますが、何卒宜しくお願い申し上げます。

                                </div>
                        </div><!--/.content-->
		<div style="text-align:center">
		<img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
		</div>
        </div><!--/#info-->
		{%include file="common/common.phtml"%}
</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}