{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
<div id="basebackground" style="background:#f3f3c5;">
	<div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
	{% if $step=="start" %}
	<div class="content" style="background:#f3f3c5;">
		<div class="headline" style="background:#aec946;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			{%$name|escape%}<br />
			<img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
		</div><!--/.headline-->
		<div class="inner">
			<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
			<div style="text-align:center;">
            <!--
			{% foreach from=$lstStar item=sdata %}
            {% if $sdata==1 %}
            <img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/goldstar_17x17.gif" width="17" height="17" />
            {% else %}<img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/silverstar_17x17.gif" width="17" height="17" />
            {% /if %}
            {% /foreach %}-->
            {%if $storeStar==6%}<img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/diamond_17x17_1.gif" width="17" height="17" />
            {%elseif $storeStar==7%}<img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/diamond_17x17_2.gif" width="17" height="17" />
            {%else%}<img src="{%$staticUrl%}/apps/tower/mobile/img/equipment/goldstar_{%$storeStar%}.gif" />
            {%/if%}
            <br />
            ※ﾚﾍﾞﾙを{%$rowStarUpInfo.star%}にするには、<br />
            お店ﾚﾍﾞﾙ{%$rowStarUpInfo.lv%}、{%$rowStarUpInfo.gb%}Gｺｲﾝ必要です<br />
        </div>
			<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
			<div style="text-align:center;">
			{% if $allowUp %}
				<a href='{% "$baseUrl/mobile/tower/starinfo?CF_floorid=`$floorId`&CF_step=confirm"|mixiurl %}'>星ｱｯﾌﾟ</a>&nbsp;&nbsp;&nbsp;<a href='{% "$baseUrl/mobile/tower/home?CF_floorid=`$floorId`"|mixiurl %}'>やめる</a><br />
			{% else %}
				≫<a href='{% "$baseUrl/mobile/tower/home?CF_floorid=`$floorId`"|mixiurl %}'>戻る</a>≪
			{% /if %}
			</div>
		</div><!--/.inner-->
    	<img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
		</div><!--/.content-->

	{% elseif $step=="confirm" %}
	<div id="complete">
		  <div class="content" style="background:#f3f3c5;">
		    <div class="headline" style="background:#aec946;color:#ffffff;text-align:center;">
		    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
		      {%$name|escape%}<br />
		      <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
	        </div>
		    <!--/.headline-->
		    <div class="inner"> <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />

		    <div style="text-align:center;">星ｱｯﾌﾟしますか？<br />
            合計<img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/goldicon_17x17.gif" width="17" height="17" align="top" />{%$gbBefore-$gbAfter%}<br />
			<img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/goldicon_17x17.gif" width="17" height="17" align="top" />{%$gbBefore%}　&rarr;　<img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/goldicon_17x17.gif" width="17" height="17" align="top" />{%$gbAfter%}<br />
		      </div>
		      <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
		      <div style="text-align: center;">
		      <form method="post" action='{% "$baseUrl/mobile/tower/starinfo"|mixiurl %}' style="text-align:center;">
				<input type="hidden" name="CF_floorid" value="{%$floorId%}" />
				<input type="hidden" name="CF_step" value="complete" />
              	<input name="ok" type="submit" value="ｱｯﾌﾟする"/>
		      </form>
		      <form method="post" action='{% "$baseUrl/mobile/tower/starinfo"|mixiurl %}' style="text-align:center;">
              	<input type="hidden" name="CF_floorid" value="{%$floorId%}" />
              	<input type="hidden" name="CF_step" value="start" />
              	<input name="cancel" type="submit" value="やめる"/>
		      </form>
		      </div>
		      <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
	        </div>
		    <!--/.inner-->
		    <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
		</div><!--/.content-->
  	</div><!--/#complete-->

  	{% elseif $step=="complete" %}
	<div id="complete">
        <div class="content" style="background:#f3f3c5;">
        	<div class="headline" style="background:#aec946;color:#ffffff;text-align:center;">
        	<img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
          星ｱｯﾌﾟ完了<br />
          <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
        </div>
        <!--/.headline-->
        <div class="inner"> <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
          <div style="text-align:center;">星ｱｯﾌﾟ完了しました！<br />
          合計<img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/goldicon_17x17.gif" width="17" height="17" align="top" />{%$gbBefore-$gbAfter%}<br />
          <img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/goldicon_17x17.gif" width="17" height="17" align="top" />{%$gbBefore%}　&rarr;　<img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/goldicon_17x17.gif" width="17" height="17" align="top" />{%$gbAfter%}<br />
          </div>
          <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
          <div style="text-align: center;"> ≫<a href='{% "$baseUrl/mobile/tower/home?CF_floorid=`$floorId`"|mixiurl %}'>ﾏｲ店舗へ</a>≪ </div>
          <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
        </div>
        <!--/.inner-->
        <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
		</div><!--/.content-->
  	</div><!--/#complete-->
	{% /if %}
</div>
	<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
	{%include file="common/common.phtml"%}
</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
