{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
<div id="basebackground" style="background:#f3f3c5;">
	<div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="itemdetailed">
          <div class="content" style="background:#f3f3c5;">
              <div class="headline" style="background:#c17f58;color:#ffffff;text-align:center;">
                  <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
              {%$itemInfo.name%}<br />
                  <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
              </div><!--/.headline-->
              <div class="inner">
                <div style="text-align:center">
                <table width="100%" border="0" cellpadding="0" cellspacing="1">
  <tr>
    <td width="68" align="center" valign="top"><img src="{%$staticUrl%}/apps/tower/mobile/img/item/{%$itemInfo.id%}.gif" style="margin:3px 0;" /></td>
    <td align="left" style=" font-size:x-small;">
    <span style="color:#0d3a89; font-size:x-small;">{%$itemInfo.name%}</span><br />
                  <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                  <span style=" font-size:x-small;">{%$itemInfo.desc%}</span><br />

    </td>
  </tr>
</table>

<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />

<form action='{% "$baseUrl/mobile/tower/useitemconfirm"|mixiurl %}' method="post">
    <input type="hidden" name="CF_itemid" value="{%$itemInfo.id%}">

<table width="212" border="0" align="center" cellpadding="0" cellspacing="1" style="background:#cece96">
  <tr>
    <td><table width="210" border="0" cellpadding="0" cellspacing="3" style="background:#f3f3c5;">
    {%foreach from=$floorsInfo item=data key=index%}
      <tr>
        <td align="left" valign="top">
          <input type="radio" name="floorId" value="{%$data.floorId%}" id="RadioGroup1_0" {%if $index==0%}checked=true{%/if%}/>

          {%$data.sysStoreName%}
        </td>
        <td align="center" valign="top">
            <img src="{%$staticUrl%}/apps/tower/mobile/img/equipment/goldstar_{%$data.star%}.gif"  border="0" />
        </td>
      </tr>
    {%/foreach%}

    </table></td>
    </tr>
</table>
<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
{%if $itemInfo.id==30%}
<table width="212" border="0" align="center" cellpadding="0" cellspacing="1" style="background:#cece96">
  <tr>
    <td><table border="0" cellpadding="0" cellspacing="0" style="background:#f3f3c5;">
      <tr>
        <td width="70" align="center"><div style="font-size:x-small;">
          <input name="storeType" type="radio" id="RadioGroup1_2" value="1" checked="checked" />
          美容院</div></td>
        <td width="70" align="center"><div style="font-size:x-small;">
          <input name="storeType" type="radio" id="RadioGroup1_3" value="2" />
          ｹｰｷ屋</div></td>
        <td width="70" align="center"><div style="font-size:x-small;">
          <input name="storeType" type="radio" id="RadioGroup1_4" value="3" />
          ｽﾊﾟ</div></td>
      </tr>
      <tr>
        <td align="center"><img src="{%$staticUrl%}/apps/tower/mobile/img/icon/60x60_01.gif" width="60" height="60"   /></td>
        <td align="center"><img src="{%$staticUrl%}/apps/tower/mobile/img/icon/60x60_02.gif" width="60" height="60"   /></td>
        <td align="center"><img src="{%$staticUrl%}/apps/tower/mobile/img/icon/60x60_03.gif" width="60" height="60"   /></td>
      </tr>
    </table></td>
  </tr>
</table>
{%/if%}
<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
{%if $itemInfo.id==32%}
引越しするﾌﾛｱのな
<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><span style="text-align:center">
    <input type="text" name="txtFloorId"  size="6" />
</span><br />
{%/if%}

                  
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
            <input type="submit" value="つかう" style="color:#000;font-size:x-small;" />
</form>
                  <form action='{% "$baseUrl/mobile/toweritem/itembox"|mixiurl %}' method="post">
                    <input type="submit" value="やめる" style="color:#000;font-size:x-small;" />
                  </form>
                  </div>
                </div>
<img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
		</div><!--/.content-->
        <!--/#landlord-->
        </div>
        </div>
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />

{%include file="common/common.phtml"%}
</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
