{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
<div id="basebackground" style="background:#f3f3c5;">
	<div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="itemdetailed">
          <div class="content" style="background:#f3f3c5;">
              <div class="headline" style="background:#c17f58;color:#ffffff;text-align:center;">
                  <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
              {%$itemInfo.name%}<br />
                  <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
              </div><!--/.headline-->
              <div class="inner">
                <div style="text-align:center">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/item/{%$itemInfo.id%}.gif" style="margin:3px 0;" />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                    <div  style="text-align:center">
                            <span style="color:red; font-size:13px;">
                                {%if $itemInfo.id==32%}
                                                                     引越しｶｰﾄﾞをつかって、ﾌﾛｱ{%$newFloorId%}に引越ししますか？
                                {%elseif $itemInfo.id==30%}
                                                                     ﾘｾｯﾄｶｰﾄﾞを使って、美容院をｹｰｷ屋に変えますか？
                                {%elseif $itemInfo.id==31%}
                                    {%$itemInfo.desc%}
                                {%/if%}
                             </span><br />
                            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                            {%if $itemInfo.id==32%}
                            <a href='{% "$baseUrl/mobile/tower/useitemcomplete?CF_itemid=`$itemInfo.id`&CF_floorid=`$floorId`&CF_newfloor=$newFloorId"|mixiurl %}'>つかう</a>&nbsp;&nbsp;
                            {%elseif $itemInfo.id==31%}
                            <a href='{% "$baseUrl/mobile/tower/useitemcomplete?CF_itemid=`$itemInfo.id`&CF_floorid=`$floorId`"|mixiurl %}'>つかう</a>&nbsp;&nbsp;
                            {%elseif $itemInfo.id==30%}
                            <a href='{% "$baseUrl/mobile/tower/useitemcomplete?CF_itemid=`$itemInfo.id`&CF_floorid=`$floorId`&CF_newstoretype=$storeType"|mixiurl %}'>つかう</a>&nbsp;&nbsp;
                            {%/if%}
                            <a href='{% "$baseUrl/mobile/tower/useitem?CF_itemid=`$itemInfo.id`"|mixiurl %}'>やめる</a>
                    </div>
                </div>
              </div>

<img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
		</div><!--/.content-->
        <!--/#landlord-->
        </div>
        </div>
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />

{%include file="common/common.phtml"%}
</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
