{%include file="header.phtml"%}

<div id="container" style="font-size:x-small;">
	<div id="basebackground" style="background:#f3f3c5;">
	<div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
	<div id="error">
	    <div class="content" style="background:#f3f3c5;">
	      <div class="inner">
			{%$errContent|escape%}
	      </div><!--/.inner-->
		  <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
		</div><!--/.content-->
	</div><!--/#error-->
	</div>
	<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
</div><!--/#container-->

{%include file="footer.phtml"%}