{%include file="header.phtml"%}

<div id="container" style="font-size:x-small;">
    <div id="basebackground" style="background:#f3f3c5;">
    <div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
    <div id="error">
        <div class="content" style="background:#f3f3c5;">
            <div class="headline" style="background:#f39b30;color:#ffffff;text-align:center;">
                <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                 {% if $msg %}ｴﾗｰ情報{% else %}不正なアクションです{% /if %}<br />
                <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
            </div><!--/.headline-->

            <div class="inner">
                <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                    <div style="text-align:center">{% if $msg %}{%$msg%}{% else %}不正なアクションが実行されました。たいへんお手数ですが、再読み込みを行った後、目的のアクションを実行してください｡{% /if %}</div>
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                <div style="text-align:center;">
                                    ≫<a href='{% "$baseUrl/mobile/towerfirst/firstgotohome?CF_floorId=$floorId&CF_guide=$guide"|mixiurl %}'>ﾏｲ店舗へ</a>≪
                </div>
          </div><!--/.inner-->

         <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
            </div><!--/.content-->
    </div><!--/#error-->
    </div>
    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />

</div><!--/#container-->

{%include file="footer.phtml"%}