{%include file="error/common/header.phtml"%}

<div id="error">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/tower/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			ｱｸｾｽｴﾗｰ<br />
			<img src="{%$staticUrl%}/apps/tower/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
		</div><!--/.headline-->
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			お探しのﾍﾟｰｼﾞが見つかりませんでした｡<br />
			<br />
			大変申し訳ございませんがｱﾌﾟﾘﾄｯﾌﾟﾍﾟｰｼﾞにお戻りください。<br />
			<br />
		</div><!--/.description-->

        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
    </div><!--/.content-->
</div><!--/#error-->

{%include file="error/common/footer.phtml"%}
