{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
<div id="basebackground" style="background:#f3f3c5;">
	<div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="complete">
            <div class="content" style="background:#f3f3c5;">
                <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                    掃除完了<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                </div><!--/.headline-->
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align: left;">すべてのゴミを片付けました。<br />
                        {%$gb%}Gｺｲﾝを手に入れました。<br />
					</div>
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align:center;">
                                            ≫<a href='{% "$baseUrl/mobile/tower/profile?CF_floorid=$floorId"|mixiurl %}'>{%if $isToOther%}{%$floorId%}階の店舗へ戻る{%else%}ﾏｲ店舗へ{%/if%}</a>≪
                    </div>
                </div><!--/.inner-->
            <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
			</div><!--/.content-->
        </div><!--/#complete-->
        </div>
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />

{%include file="common/common.phtml"%}

</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
