{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
<div id="basebackground" style="background:#f3f3c5;">
	<div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="complete">
            <div class="content" style="background:#f3f3c5;">
            <div class="headline" style="background:#dc6221;color:#ffffff;text-align:center;">
            <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
            {%$ownerInfo.nickname|escape%}の{%$storeName %}<br />
            <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" />
            <div class="headline" style="background:#dc6221;color:#ffffff;text-align:center;">
                    {%if $type=="1"%}追加完了{%elseif $type=="2"%}ﾚﾍﾞﾙｱｯﾌﾟ完了{%/if%} <br />
                </div><!--/.headline-->
            </div>
            
    		<!--/.headline-->
                
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align: left;">
                   {%if $chairType=="wait"%}待合用椅子を{%else%}接客用椅子を{%/if%}{%if $type=="1"%}追加{%elseif $type=="2"%}ﾚﾍﾞﾙｱｯﾌﾟ{%/if%}しました。</div>
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align:center;">
                        ≫<a href='{% "$baseUrl/mobile/tower/home?CF_floorid=$floorId"|mixiurl %}'>ﾏｲ店舗へ</a>≪
                    </div>
                </div><!--/.inner-->
            <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
		</div><!--/.content-->
        </div><!--/#complete-->
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
</div>
{%include file="common/common.phtml"%}
</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
