{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
<div id="basebackground" style="background:#f3f3c5;">
        <div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="complete">
            <div class="content" style="background:#f3f3c5;">
                <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                    勧誘成功<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                </div><!--/.headline-->
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />

                    <div style="text-align:center;">
                    <object data="{%$staticUrl%}/apps/tower/mobile/swf/character/{%$ctp%}.swf" type="application/x-shockwave-flash" width="100"   height="110">
                    <param name="bgcolor" value="#f3f3c5">
                    <param name="loop" value="off">
                    <param name="quality" value="high">
                    <!--<embed src="{%$staticUrl%}/apps/tower/mobile/swf/character/{%$ctp%}.swf" width="100" height="110" loop="on" quality="high"   bgcolor="#000000"></embed>-->
                    </object>
		<!--<img src="{%$staticUrl%}/apps/tower/mobile/img/character/v1/{%$ctp%}.gif" width="64" height="79" />-->
                    </div>
					<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align:center">勧誘成功！</div>
                    <div style="text-align: left;">お客様を自分の店舗へ勧誘しました。</div>
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align: center;">
                        {%*<a href='{% "$baseUrl/mobile/towerservice/waitingroom?CF_floorid=`$floorId`&CF_storeType=`$type`"|mixiurl %}'>さっそく、座席に案内する</a>≪*%}
                        {%*<a href='{% "$baseUrl/mobile/towerflash/store?CF_floorid=`$floorId`&CF_from=waitingroomothers-CF_stealfloorid-`$stealFloorId`-CF_inneruid-`$innerUid`&CF_chairid=`$chairId`&CF_isfirst=n&CF_action=setSeat&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$uid`&rand=`$rand`"|mobile_flashurl %}' accesskey="5" style="font-size:medium">{%emoji code="F98B"%}お客様を接客する</a><br />*%}
                        <a href='{% "$baseUrl/mobile/towerservice/guideseat?CF_floorid=`$floorId`&CF_chairid=`$chairId`&CF_guestid=`$ctp`"|mixiurl %}' accesskey="5" style="font-size:medium">{%emoji code="F98B"%}お客様を接客する</a><br />
						<a href='{% "$baseUrl/mobile/towerservice/friendstorelist?CF_floorid=`$floorId`&CF_type=`$type`"|mixiurl %}'>≫他のお客様を勧誘しに行く≪</a><br />
                    </div>
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                </div><!--/.inner-->
                <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
			</div><!--/.content-->
        </div><!--/#complete-->
        </div>
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />

{%include file="common/common.phtml"%}
</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}