{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
	<div id="basebackground" style="background:#f3f3c5;">
        <div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="service">
            <div class="content" style="background:#f3f3c5;">
                <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                    注文受付<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                </div><!--/.headline-->
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align:center">
                    注文を受け付けました<br />
                    </div>
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" />
                        {%if !$isServiceSeatFull%}
                            <div style="font-size:x-small; text-align:center">
                                <a href='{% "$baseUrl/mobile/towerservice/waitingroom?CF_floorid=`$floorId`&CF_storeType=`$storeType`"|mixiurl %}' accesskey="5" style="font-size:medium">{%emoji code="F98B"%}次の人を案内する</a>
                            </div>
                        {%else%}
                            <div style="font-size:x-small; text-align:center">満席になりました</div>
                        {%/if%}
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" />


                    <div class="section">
                        <table align="center" width="100%">
                            <tr>
                                <td width="100" rowspan="7" align="center" valign="top" style="vertical-align:top">
                                <!--
                                    <img src="{%$staticUrl%}/apps/tower/mobile/img/character/v1/{%$result.tp%}.gif" width="64" height="79" align="top" />
                                -->
                                    <object data="{%$staticUrl%}/apps/tower/mobile/swf/service/{%$result.tp%}_{%$guestAction%}.swf" type="application/x-shockwave-flash" width="100" height="110">
                                        <param name="bgcolor" value="f3f3c5">
                                        <param name="loop" value="on">
                                        <param name="quality" value="high">
                                    </object>
                                </td>
                                <td>
                                  <div style="font-size:x-small; text-align:left;">作業終了時間<br /><img src="{%$staticUrl%}/apps/tower/mobile/img/confirmlist/speed_66x14_{%$result.spPic%}.gif" width="66" height="14" />{%$result.lev_hour%}:{%$result.lev_min%}<br /><a href='{% "$baseUrl/mobile/towerservice/speeduplist?CF_floorId=$floorId&CF_chairid=$chairid"|mixiurl %}'>加速する</a></div>
                                </td>
                            </tr>
                            <tr>
                                <td><div style="font-size:x-small; text-align:left;">ﾑｰﾄﾞ指数:{%emoji code=$result.ha_emoj%}<br /><img src="{%$staticUrl%}/apps/tower/mobile/img/confirmlist/enarge_66x14_{%$moodPic%}.gif" width="66" height="14" />{%$result.ha%}/100<br />{%if $result.ha<100%}<a href='{% "$baseUrl/mobile/towerservice/mooduplist?CF_floorId=$floorId&CF_chairid=$chairid&CF_oldMood=$mood"|mixiurl %}'>ﾑｰﾄﾞを上げる</a>{%/if%}</div></td>
                            </tr>
                        </table>


                  </div><!--/.section-->
                  <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                  <div style="background:#c17f58;text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" /></div>
                  <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
				<div style="text-align:center">
                                        ≫<a href='{% "$baseUrl/mobile/tower/home?CF_floorid=`$floorId`"|mixiurl %}'>ﾏｲ店舗へ戻る</a>≪<br>
                                        ≫<a href='{% "$baseUrl/mobile/towerdetail/storedetail?CF_storetype=`$storeInfo.type`&CF_floorid=`$floorId`"|mixiurl %}'>店舗詳細</a>≪<br>
                </div>
			<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                </div><!--/.inner-->
                <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
            </div><!--/.content-->
        </div><!--/#service-->
        </div>
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />

{%include file="common/common.phtml"%}
</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
