{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
	<div id="basebackground" style="background:#f3f3c5;">
        <div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="complete">
            <div class="content" style="background:#f3f3c5;">
                <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                    注文を受け付けましょう！<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                </div><!--/.headline-->
                {%if !$errorHappend%}
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align: center">お客様を案内しました<br />
                                                ﾑｰﾄﾞ<span style=" color:#00C">{%$oldMood%}&rarr;{%$newMood%}</span><br />

                            {%if $waitServiceGuest.ac_count==0%}{%else%}
                                <a href='{% "$baseUrl/mobile/towerservice/giveservice?CF_itemid=`$waitServiceGuest.ac`&CF_floorid=$floorid&CF_chairid=`$waitServiceGuest.toChairId`&CF_count=$waitServiceGuestCount&CF_stealfloorid=$stealfloorid&CF_inneruid=$inneruid"|mixiurl %}' accesskey="5" style="font-size:medium">{%emoji code="F98B"%}注文をきく</a>
                            {%/if%}
                    </div>
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div class="section">
                        <table align="center" width="100%">
                            <tr>
                                <td rowspan="3" width="68" align="center" style="text-align:center; vertical-align:top;">
                                    <img src="{%$staticUrl%}/apps/tower/mobile/img/character/v1/{%$waitServiceGuest.tp%}.gif" width="64" height="79" align="top" />
                                </td>
                                <td><div style="font-size:x-small; text-align:left;">{%$waitServiceGuest.ac_name%}をお願いします。<br />名前:{%$waitServiceGuest.guest_name%}</div></td>
                            </tr>
                            <tr>
                                <td><div style="font-size:x-small; text-align:left;"><span style="color:#f5102b;">ﾚﾍﾞﾙ:{%$waitServiceGuest.tp%}</span></div></td>
                            </tr>
                            <tr>
                                <td>
                                    <div style="font-size:x-small; text-align:left;">ﾑｰﾄﾞ指数:{%emoji code=$waitServiceGuest.mood_emoj%}<br />
                                        <img src="{%$staticUrl%}/apps/tower/mobile/img/confirmlist/enarge_66x14_{%$waitServiceGuest.moodPic%}.gif" width="66" height="14" />{%$waitServiceGuest.ha%}/100
                                    </div>
                                </td>
                            </tr>
                        </table>

                        <div style="text-align:center;">
                            {%if $waitServiceGuest.ac_count==0%}
                                <span style="color:#f5102b;">ｱｲﾃﾑがありません。</span><br />
                                                                ≫<a href='{% "$baseUrl/mobile/towershop/buyitemfromservicepage?CF_itemId=`$waitServiceGuest.ac`&CF_floorid=$floorid"|mixiurl %}'>ｱｲﾃﾑそろえる</a>
                            {%/if%}
                        </div>
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                        <div style="background:#063d71;text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" /></div>
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                    </div><!--/.section-->
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                </div><!--/.inner-->
                {%else%}
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align: center">
                                                    案内が失敗してしまいました。<br>
                        <a href='{% "$baseUrl/mobile/towerservice/waitingroom?CF_floorid=$floorid&CF_storeType=$storeType"|mixiurl %}'>お客様からの注文をきく</a>
                    </div>
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                </div><!--/.inner-->
                {%/if%}
            	<img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
</div><!--/.content-->
        </div><!--/#complete-->
        </div><!--/#basebackground-->
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />

{%include file="common/common.phtml"%}

</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
