{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<body style="background:#67bdde;color:#392007;">

    <div id="container" style="font-size:x-small;">

        <div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="basebackground" style="background:#f3f3c5;">
            <div id="shop">
                <div class="content" style="background:#f3f3c5;">
                  <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                      <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                                                    お客様をイスへ案内する<br />
                      <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                  </div><!--/.headline-->
                </div><!--/.content-->
                <table><tr><td></td></tr></table>
                <div class="content" style="text-align:center;width:240px;margin:0px auto;">
                    {%if $lv7Chairs%}
                    <div style="text-align:left;font-size:x-small;width:150px;margin:0px auto;">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/equipment/work_chair_{%$chairName%}_7.gif" style="float:left;margin-right:10px" align="left" />
                                                        ｲｽLv:7級イス<br />
                                                        空席:{%$lv7Chairs.count%}<br />
                        {%if $lv7Chairs.count>0%}<a href='{% "$baseUrl/mobile/towerservice/guideseatcomplete?CF_floorid=`$floorId`&CF_chairid=`$waitChairId`&CF_ha=`$guestMood`&CF_guestCount=`$guestCount`&selid=`$lv7Chairs.chairId`"|mixiurl %}'>案内する</a>{%else%}全て使用中です{%/if%}
                    </div>
                    <div style="text-align:center;clear:both;" clear="all">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" style="margin:10px 0px;" />
                    </div>
                    {%/if%}
                    {%if $lv6Chairs%}
                    <div style="text-align:left;font-size:x-small;width:150px;margin:0px auto;">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/equipment/work_chair_{%$chairName%}_6.gif" style="float:left;margin-right:10px" align="left" />
                                                        ｲｽLv:6級イス<br />
                                                        空席:{%$lv6Chairs.count%}<br />
                        {%if $lv6Chairs.count>0%}<a href='{% "$baseUrl/mobile/towerservice/guideseatcomplete?CF_floorid=`$floorId`&CF_chairid=`$waitChairId`&CF_ha=`$guestMood`&CF_guestCount=`$guestCount`&selid=`$lv6Chairs.chairId`"|mixiurl %}'>案内する</a>{%else%}全て使用中です{%/if%}
                    </div>
                    <div style="text-align:center;clear:both;" clear="all">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" style="margin:10px 0px;" />
                    </div>
                    {%/if%}
                    {%if $lv5Chairs%}
                    <div style="text-align:left;font-size:x-small;width:150px;margin:0px auto;">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/equipment/work_chair_{%$chairName%}_5.gif" style="float:left;margin-right:10px" align="left" />
                                                        ｲｽLv:5級イス<br />
                                                        空席:{%$lv5Chairs.count%}<br />
                        {%if $lv5Chairs.count>0%}<a href='{% "$baseUrl/mobile/towerservice/guideseatcomplete?CF_floorid=`$floorId`&CF_chairid=`$waitChairId`&CF_ha=`$guestMood`&CF_guestCount=`$guestCount`&selid=`$lv5Chairs.chairId`"|mixiurl %}'>案内する</a>{%else%}全て使用中です{%/if%}
                    </div>
                    <div style="text-align:center;clear:both;" clear="all">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" style="margin:10px 0px;" />
                    </div>
                    {%/if%}
                    {%if $lv4Chairs%}
                    <div style="text-align:left;font-size:x-small;width:150px;margin:0px auto;">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/equipment/work_chair_{%$chairName%}_4.gif" style="float:left;margin-right:10px" align="left" />
                                                        ｲｽLv:4級イス<br />
                                                        空席:{%$lv4Chairs.count%}<br />
                        {%if $lv4Chairs.count>0%}<a href='{% "$baseUrl/mobile/towerservice/guideseatcomplete?CF_floorid=`$floorId`&CF_chairid=`$waitChairId`&CF_ha=`$guestMood`&CF_guestCount=`$guestCount`&selid=`$lv4Chairs.chairId`"|mixiurl %}'>案内する</a>{%else%}全て使用中です{%/if%}
                    </div>
                    <div style="text-align:center;clear:both;" clear="all">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" style="margin:10px 0px;" />
                    </div>
                    {%/if%}
                    {%if $lv3Chairs%}
                    <div style="text-align:left;font-size:x-small;width:150px;margin:0px auto;">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/equipment/work_chair_{%$chairName%}_3.gif" style="float:left;margin-right:10px" align="left" />
                                                        ｲｽLv:3級イス<br />
                                                        空席:{%$lv3Chairs.count%}<br />
                        {%if $lv3Chairs.count>0%}<a href='{% "$baseUrl/mobile/towerservice/guideseatcomplete?CF_floorid=`$floorId`&CF_chairid=`$waitChairId`&CF_ha=`$guestMood`&CF_guestCount=`$guestCount`&selid=`$lv3Chairs.chairId`"|mixiurl %}'>案内する</a>{%else%}全て使用中です{%/if%}
                    </div>
                    <div style="text-align:center;clear:both;" clear="all">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" style="margin:10px 0px;" />
                    </div>
                    {%/if%}
                    {%if $lv2Chairs%}
                    <div style="text-align:left;font-size:x-small;width:150px;margin:0px auto;">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/equipment/work_chair_{%$chairName%}_2.gif" style="float:left;margin-right:10px" align="left" />
                                                        ｲｽLv:2級イス<br />
                                                        空席:{%$lv2Chairs.count%}<br />
                        {%if $lv2Chairs.count>0%}<a href='{% "$baseUrl/mobile/towerservice/guideseatcomplete?CF_floorid=`$floorId`&CF_chairid=`$waitChairId`&CF_ha=`$guestMood`&CF_guestCount=`$guestCount`&selid=`$lv2Chairs.chairId`"|mixiurl %}'>案内する</a>{%else%}全て使用中です{%/if%}
                    </div>
                    <div style="text-align:center;clear:both;" clear="all">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" style="margin:10px 0px;" />
                    </div>
                    {%/if%}
                    {%if $lv1Chairs%}
                    <div style="text-align:left;font-size:x-small;width:150px;margin:0px auto;">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/equipment/work_chair_{%$chairName%}_1.gif" style="float:left;margin-right:10px" align="left" />
                                                        ｲｽLv:1級イス<br />
                                                        空席:{%$lv1Chairs.count%}<br />
                        {%if $lv1Chairs.count>0%}<a href='{% "$baseUrl/mobile/towerservice/guideseatcomplete?CF_floorid=`$floorId`&CF_chairid=`$waitChairId`&CF_ha=`$guestMood`&CF_guestCount=`$guestCount`&selid=`$lv1Chairs.chairId`"|mixiurl %}'>案内する</a>{%else%}全て使用中です{%/if%}
                    </div>
                    <div style="text-align:center;clear:both;" clear="all">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" style="margin:10px 0px;" />
                    </div>
                    {%/if%}
                </div>
            </div>
        <div style="text-align:center">
            <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
        </div>
        </div><!--/#basebackground -->

{%include file="common/common.phtml"%}
</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
