{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
 <div id="basebackground" style="background:#f3f3c5;">
	<div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="complete">
            <div class="content" style="background:#f3f3c5;">
                <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                    加速完了<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                </div><!--/.headline-->
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align:center">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/character/v1/{%$guestId%}.gif" width="64" height="79"/>
                    </div>

                    <div style="text-align:left;">お客様の作業終了までの時間が短縮されました。<br>
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    {%if $speedEnd%}
                        <div style="text-align:center">
                    	<span style=" color:#3c9607">作業が終了しました。</span><br />
                            <a href='{% "$baseUrl/mobile/towerservice/pickupmoney?CF_floorid=`$floorId`&CF_storeType=`$storeType`&CF_seatids=`$chairId`"|mixiurl %}'>集　金</a>
                        </div>
                    {%else%}
                        <span style=" color:#3c9607">作業終了時間&nbsp;{%$oldHour%}:{%$oldMinute%}&rarr;{%$newHour%}:{%$newMinute%}</span>
                    {%/if%}
                    </div>
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align:center;">
                    {%*
                        {%if $item.count>0%}
                            <a href='{% "$baseUrl/mobile/towerservice/speedupconfirm?CF_floorid=`$floorId`&CF_storeType=`$storeType`&CF_itemid=`$item.id`&CF_isother=$isToOther"|mixiurl %}' accesskey="5" style="font-size:medium">{%emoji code="F98B"%}他のお客様も加速</a><br />
                        {%/if%}
                        {%if !$isToOther%}
                            <a href='{% "$baseUrl/mobile/towerservice/speeduplist?CF_floorId=`$floorId`&CF_storeType=`$storeType`"|mixiurl %}'>≫他のｱｲﾃﾑを使う≪</a><br />
                        {%/if%}
                    *%}
                    <a href='{% "$baseUrl/mobile/towerdetail/storedetail?CF_floorid=`$floorId`&CF_storetype=`$storeType`"|mixiurl %}'>店舗詳細</a>
                    </div>

                </div><!--/.inner-->
            <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
		</div><!--/.content-->
        </div><!--/#complete-->
        </div>
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
{%include file="common/common.phtml"%}
</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
