{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
	<div id="basebackground" style="background:#f3f3c5;">
        <div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="confirmlist">
            <div class="content" style="background:#f3f3c5;">
                <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                    注文待ちお客様<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                </div><!--/.headline-->
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    {%if $countService==0%}
                    注文待ちお客様がいません。<br />
                    {%else%}
                    {%$countService%}人のお客様が注文待ちです。<br />
                    {%/if%}
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />

                    {%foreach from=$waitServiceList item=data%}
                    <div class="section">
                        <table align="center" width="100%">
                            <tr>
                                <td rowspan="3" width="68" align="center" style="text-align:center; vertical-align:top;">
                                    <img src="{%$staticUrl%}/apps/tower/mobile/img/character/v1/{%$data.tp%}.gif" width="64" height="79" align="top" />
                        </td>
                                <td><div style="font-size:x-small; text-align:left;">「{%$data.ac_name%}をお願いします。」<br />名前:{%$data.name%}</div></td>
                            </tr>
                            <tr>
                                <td><div style="font-size:x-small; text-align:left;"><span style="color:#f5102b;">ﾚﾍﾞﾙ:{%$data.tp%}</span></div></td>
                            </tr>
                            <tr>
                                <td>
                                    <div style="font-size:x-small; text-align:left;">ﾑｰﾄﾞ指数:{%emoji code=$data.ha_emoj%}<br />
                                        <img src="{%$staticUrl%}/apps/tower/mobile/img/confirmlist/enarge_66x14_{%$data.moodPic%}.gif" width="66" height="14" />{%$data.ha%}/100<br />
                                        {%$data.remain_hour%}時間{%$data.remain_minute%}分後に席を離れます
                                    </div>
                                </td>
                            </tr>
                        </table>

                        <div style="text-align:right;">
                            {%if $data.ac_count==0%}
                                <span style="color:#f5102b;">ｱｲﾃﾑがありません。</span><br />
                                                                ≫<a href='{% "$baseUrl/mobile/towershop/buyitemfromservicepage?CF_itemId=`$data.ac`&CF_floorid=$floorid"|mixiurl %}'>ｱｲﾃﾑそろえる</a>
                            {%else%}
                                                                ≫<a href='{% "$baseUrl/mobile/towerservice/giveservice?CF_itemid=`$data.ac`&CF_floorid=$floorid&CF_chairid=`$data.y`&CF_count=$countService"|mixiurl %}'>注文をきく</a>
                            {%/if%}
                        </div>
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                        <div style="background:#063d71;text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" /></div>
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                    </div><!--/.section-->
                {%/foreach%}
		<div style="text-align:center">≫<a href='{% "$baseUrl/mobile/tower/home?CF_floorid=`$floorid`"|mixiurl %}'>ﾏｲ店舗へ戻る</a>≪</div>
                </div><!--/.inner-->
                <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
            </div><!--/.content-->
        </div><!--/#confirmlist-->
        </div>
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
    {%include file="common/common.phtml"%}
    </div><!--/#container-->
    {%include file="footer_ad.phtml"%}
    {%include file="footer.phtml"%}
