{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
<div id="basebackground" style="background:#f3f3c5;">
	<div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="complete">
            <div class="content" style="background:#f3f3c5;">
                <div class="headline" style="background:#c17f58;color:#ffffff;text-align:center;">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                    購入完了<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                </div><!--/.headline-->
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align: left;">{%$itemInfo.name%}<br />
                    {%$buyNum%}つ購入しました。<br />
                    合計<img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/{%if $moneyType=='g'%}goldicon_17x17.gif{%elseif $moneyType=='m'%}micon_17x17.gif{%/if%}" width="17" height="17" align="top" />{%$allMoney-$leaveMoney%}<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/{%if $moneyType=='g'%}goldicon_17x17.gif{%elseif $moneyType=='m'%}micon_17x17.gif{%/if%}" width="17" height="17" align="top" />{%$allMoney%}
                    &nbsp;&rarr;&nbsp;
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/{%if $moneyType=='g'%}goldicon_17x17.gif{%elseif $moneyType=='m'%}micon_17x17.gif{%/if%}" width="17" height="17" align="top" />{%$leaveMoney%}</div>
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align:center;">
                        {%if $chairId%}
                            {%if $action=='speed'%}
                                                            ≫<a href='{% "$baseUrl/mobile/towerservice/speedupcomplete?CF_floorid=$floorId&CF_chairid=$chairId&CF_itemid=$itemId"|mixiurl %}'>つかう</a>≪<br />
                            {%/if%}
                            {%if $action=='mood'%}
                                                            ≫<a href='{% "$baseUrl/mobile/towerservice/moodupcomplete?CF_floorid=$floorId&CF_chairid=$chairId&CF_itemid=$itemId&CF_oldMood=$oldMood"|mixiurl %}'>つかう</a>≪<br />
                            {%/if%}
                        {%/if%}
                                                    ≫<a href='{% "$baseUrl/mobile/toweritem/itembox"|mixiurl %}'>ｱｲﾃﾑ箱へ</a>≪<br />
                                                    ≫<a href='{% "$baseUrl/mobile/towershop/shop"|mixiurl %}'>ｼｮｯﾌﾟに戻る</a>≪
                    </div>
                </div><!--/.inner-->
               <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
            </div><!--/.content-->
        </div><!--/#complete-->
</div>
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />

{%include file="common/common.phtml"%}
</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
