{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
<div id="basebackground" style="background:#f3f3c5;">
	<div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="shop">
          <div class="content" style="background:#f3f3c5;">
              <div class="headline" style="background:#c17f58;color:#ffffff;text-align:center;">
                  <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                  ｼｮｯﾌﾟ<br />
                  <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
              </div><!--/.headline-->
              <div class="classification" style="text-align:center;">
<div class="userinfo"><table width="220" cellpadding="3" cellspacing="1" border="0" align="center" style="background:#d9e3b9;">
							<tr>
								<td style="background:#ffffee;text-align:center;"><div style="font-size:x-small;">
								{%emoji code="F9A0"%}<span style="color:#f5102b;">Lv{%$userInfo.level%}</span> [経験:<span style="color:#a70f0f;">{%$userInfo.cexp%}</span>/{%$userInfo.allexp%}]<br />
								<span class="classification" style="text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/goldicon_17x17.gif" width="17" height="17" align="top" /></span>{%$gb%} <span class="classification" style="text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/micon_17x17.gif" width="17" height="17" align="top" /></span>{%$mb%}</div></td>
							</tr>
						</table></div><!--/.userinfo-->


            <br />
            [{%if $type==0%}全部{%else%}<a href='{% "$baseUrl/mobile/towershop/shop?CF_type=0"|mixiurl %}'>全部</a>{%/if%}|{%if $type==1%}常用{%else%}<a href='{% "$baseUrl/mobile/towershop/shop?CF_type=1"|mixiurl %}'>常用</a>{%/if%}|{%if $type==2%}道具{%else%}<a href='{% "$baseUrl/mobile/towershop/shop?CF_type=2"|mixiurl %}'>道具</a>{%/if%}|{%if $type==3%}ｶｰﾄﾞ{%else%}<a href='{% "$baseUrl/mobile/towershop/shop?CF_type=3"|mixiurl %}'>ｶｰﾄﾞ</a>{%/if%}|{%if $type==4%}その他{%else%}<a href='{% "$baseUrl/mobile/towershop/shop?CF_type=4"|mixiurl %}'>その他</a>{%/if%}]<br />

             {%if $type==1%}{% if $mtype==0%}全部{%else%}<a href='{% "$baseUrl/mobile/towershop/shop?CF_type=1&CF_type1=0"|mixiurl %}'>全部</a>{%/if%}|{% if $mtype==1%}美容院{%else%} <a href='{% "$baseUrl/mobile/towershop/shop?CF_type=1&CF_type1=1"|mixiurl %}'>美容院</a>{%/if%}|{% if $mtype==2%}ｹｰｷ屋{%else%}<a href='{% "$baseUrl/mobile/towershop/shop?CF_type=1&CF_type1=2"|mixiurl %}'>ｹｰｷ屋</a>{%/if%}|{% if $mtype==3%}ｽﾊﾟ{%else%}<a href='{% "$baseUrl/mobile/towershop/shop?CF_type=1&CF_type1=3"|mixiurl %}'>ｽﾊﾟ</a>{%/if%}<br />
             {%/if%}
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
            <div style="background:#c17f58;text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" /></div>
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />

            <div class="inner">
              {%if $itemList==null%}
                                 いよいよ新しい商品が出ます。期待してもいいですよ！
              {%else%}
              {% foreach from=$itemList item=data%}
                  <div class="section">
                    <form name="item{%$data.id%}" action='{% "$baseUrl/mobile/towershop/buyitemconfirm"|mixiurl %}' method="post">
                    <input type="hidden" name="CF_id" value="{%$data.id%}">
                    <input type="hidden" name="CF_nm" value="{%$data.nm%}">
                    <input type="hidden" name="CF_moneytype" value="{%$data.buy%}">
                    <table width="100%" cellpadding="0" cellspacing="0" border="0">
                      <tr>
                        <td width="65" valign="top" style="width:68px;text-align:center; vertical-align:top"><img src="{%$staticUrl%}/apps/tower/mobile/img/item/{%$data.id%}.gif" style="margin:3px 0;" /></td>
                        <td align="left"><div style="font-size:x-small;">
                        <a href='{% "$baseUrl/mobile/towershop/buyitemconfirm?CF_view=1&CF_id=`$data.id`&CF_moneytype=`$data.buy`&CF_type=$type&CF_page=$pageIndex&CF_mtype=$mtype"|mixiurl %}'>{%$data.name%}</a><br />
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/{%if $data.buy=='g'%}goldicon_17x17.gif{%else%}micon_17x17.gif{%/if%}" width="17" height="17" align="top" />{%$data.price%}<br />
                                                保有数：{%$data.nm%}個<br />
                        {%if $data.buy=='g'%}
                          {%if $gb>=$data.price%}
                          <select name="select">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                          </select>
                          &nbsp;&nbsp;&nbsp;<input type="submit" value="購入" style="color:#000;font-size:x-small;"></div></td>
                          {%else%}所持金不足です
                          {%/if%}
                        {%elseif $data.buy=='m'%}
                            {%if $mb>=$data.price%}
                              <select name="select">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                                <option value="10">10</option>
                              </select>
                              &nbsp;&nbsp;&nbsp;<input type="submit" value="購入" style="color:#000;font-size:x-small;"></div></td>
                              {%else%}所持金不足です
                            {%/if%}
                        {%/if%}
                      </tr>
                    </table>
                    </form>
              <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                      <div style="background:#c17f58;text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" /></div>
                      <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                  </div><!--/.section-->

                {%/foreach %}
                {%/if%}
                <div class="page" style="text-align: center;">
                    {%include file="common/pager.phtml"%}<br />
                </div>
            </div><!--/.inner-->
            <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" align="bottom"/>
          </div><!--/.content-->
        <!--/#landlord-->
        </div>
		</div>
        </div>
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" />
{%include file="common/common.phtml"%}
<!--/#container-->
</div>
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
