{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<body style="background:#67bdde;color:#392007;">

    <div id="container" style="font-size:x-small;">

        <div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="basebackground" style="background:#f3f3c5;">
            <div id="shop">
                <div class="content" style="background:#f3f3c5;">
                  <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                      <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                                                    お客様をイスへ案内する<br />
                      <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                  </div><!--/.headline-->
                </div><!--/.content-->
                <table><tr><td></td></tr></table>
                <div class="content" style="text-align:center;width:240px;margin:0px auto;">
                    {%if $lv1Chairs%}
                    <div style="text-align:left;font-size:x-small;width:150px;margin:0px auto;">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/equipment/work_chair_{%$chairName%}_1.gif" style="float:left;margin-right:10px" align="left" />
                                                        ｲｽLv:1級イス<br />
                                                        空席:{%$lv1Chairs.count%}<br />
                        {%if $lv1Chairs.count>0%}<a href='{% "$baseUrl/mobile/towerfirst/firstmoveguest?CF_floorid=`$floorId`&CF_chairid=`$waitChairId`&CF_ha=`$guestMood`&selid=`$lv1Chairs.chairId`"|mixiurl %}'>案内する</a>{%else%}全て使用中です{%/if%}
                    </div>
                    <div style="text-align:center;clear:both;" clear="all">
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" style="margin:10px 0px;" />
                    </div>
                    {%/if%}
                </div>
            </div>
        </div><!--/#basebackground -->

</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
