{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
<div id="basebackground" style="background:#f3f3c5;">
	<div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="confirmlist">
            <div class="content" style="background:#f3f3c5;">
                <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                    注文を受け付けましょう！<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                </div><!--/.headline-->
                <div class="inner">
                    {%foreach from=$waitServiceList item=data%}
                    <div style="text-align:center;">
                                                ≫<a href='{% "$baseUrl/mobile/towerfirst/firstserviceguest?CF_floorid=$floorId&CF_chairid=`$data.y`&CF_itemid=`$data.ac`"|mixiurl %}'>注文をきく</a>≪
                    </div>
                    <div class="section">
                        <table align="center" width="100%">
                            <tr>
                                <td width="70" rowspan="3" align="center" valign="top" style="text-align:center; vertical-align:top;">
                                    <img src="{%$staticUrl%}/apps/tower/mobile/img/character/v1/{%$data.tp%}.gif" width="64" height="79" align="top" />
                                </td>
                              <td><div style="font-size:x-small; text-align:left;">「{%$data.ac_name%}をお願いします」<br />名前:{%$data.name%}</div></td>
                            </tr>
                            <tr>
                                <td><div style="font-size:x-small; text-align:left;"><span style="color:#f5102b;">ﾚﾍﾞﾙ:{%$data.tp%}</span></div></td>
                            </tr>
                            <tr>
                                <td>
                                    <div style="font-size:x-small; text-align:left;">ﾑｰﾄﾞ指数:{%emoji code=$data.ha_desc%}<br />
                                        <img src="{%$staticUrl%}/apps/tower/mobile/img/confirmlist/enarge_66x14_{%$data.ha_pic%}.gif" width="66" height="14" />{%$data.ha%}/100
                                    </div>
                                </td>
                            </tr>
                        </table>


                        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                        <div style="background:#063d71;text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" /></div>
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                    </div><!--/.section-->
                {%/foreach%}
                </div><!--/.inner-->
                <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
			</div><!--/.content-->
        </div><!--/#confirmlist-->
        </div>
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />

</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
