{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
		<div id="basebackground" style="background:#f3f3c5;">
        <div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="debut">
            <div class="content" style="background:#f3f3c5;">
                <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                    ﾌﾛｱの賃貸<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                </div><!--/.headline-->
                <div class="inner">
                <form method="post" action='{% "$baseUrl/mobile/towerfirst/firstopenstoreconfirm"|mixiurl %}'>
                    <input type="hidden" name="CF_floorid" value="{%$floor%}">

                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    第{%$floor%}ﾌﾛｱを借りて開店しますか<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
					開店したいお店ﾀｲﾌﾟを選んでくださいください<br />

                    <table border="0" align="center" cellpadding="0" cellspacing="0" style="background:#f3f3c5;">
                          <tr>
                            <td bgcolor="#FF9900" colspan="3"><div style="font-size:x-small;">お店のﾀｲﾌﾟを選択してください</div></td>
                          </tr>
                          <tr>
                            <td width="80" align="center"><div style="font-size:x-small;">
                              <input name="store_type" type="radio" id="RadioGroup1_0" value="1" {%if $storeType==1%}checked="checked"{%/if%} />美容院</div></td>
                            <td width="80" align="center"><div style="font-size:x-small;">
                              <input name="store_type" type="radio" id="RadioGroup1_2" value="2" {%if $storeType==2%}checked="checked"{%/if%}/>ｹｰｷ屋</div></td>
                            <td width="80" align="center"><div style="font-size:x-small;">
                              <input name="store_type" type="radio" id="RadioGroup1_3" value="3" {%if $storeType==3%}checked="checked"{%/if%}/>ｽﾊﾟ</div></td>
                          </tr>
                          <tr>
                            <td align="center"><img src="{%$staticUrl%}/apps/tower/mobile/img/icon/60x60_01.gif" width="60" height="60"   /></td>
                            <td align="center"><img src="{%$staticUrl%}/apps/tower/mobile/img/icon/60x60_02.gif" width="60" height="60"   /></td>
                            <td align="center"><img src="{%$staticUrl%}/apps/tower/mobile/img/icon/60x60_03.gif" width="60" height="60"   /></td>
                          </tr>
                          <tr>
                            <td colspan="3" align="center">
                              {%if $enterStoreName%}
                              <input name="storeName" type="text" value="{%$enterStoreName%}" size="30" maxlength="9"/>
                              {%else%}
                              <input name="storeName" type="text" value="お店の名前を入力" size="30" maxlength="9"/>
                              {%/if%}
                            </td>
                          </tr>
                          <tr>
                            <td colspan="3" align="center"><span style="color:#f5102b;font-size:x-small;">※9文字以内</span></td>
                          </tr>
                        </table>
                <div style="text-align:center;">

                </div><br />

                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                    <div style="text-align:center;"><input type="submit" value="確認" style="color:#000;font-size:x-small;" /></div>
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                </form>
                <span style="color:#F00;">このｱﾌﾟﾘは性別を公開する仕組みになっております。</span>
                </div><!--/.inner-->
            <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
			</div><!--/.content-->
        </div><!--/#debut-->
        </div>
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
