{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
		<div id="basebackground" style="background:#f3f3c5;">
        <div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="waitingroom">
            <div class="content" style="background:#f3f3c5;">
            <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
            <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
            {%$user.nickname|escape%}の{% if $storeType==1 %}美容院{% elseif $storeType==2 %}ｹｰｷ屋{% else %}ｽﾊﾟ{% /if %}<br />
            待合室<br />
            <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /></div>
      <!--/.headline-->
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    {%$guestCount%}人のお客様がお待ちです<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    {%foreach from=$waitGuestList item=data key=index%}
                    <div class="section">
                        <table align="center" width="100%">
                            <tr>
                                <td rowspan="3" width="68" align="center" style="text-align:center; vertical-align:top;"><img src="{%$staticUrl%}/apps/tower/mobile/img/character/v1/{%$data.tp%}.gif" width="64" height="79" align="top" /></td><td style="text-align:left;"><div style="font-size:x-small;">名前：{%$data.name%}</div></td>
                          </tr>
                            <tr>
                                <td style="text-align:left;"><div style="font-size:x-small;"><span style="color:#f5102b;">Level:{%$data.tp%}</span></div></td>
                            </tr>
                            <tr>
                                <td style="text-align:left;"><div style="font-size:x-small;">ﾑｰﾄﾞ指数:{%emoji code=$data.ha_desc%}<br /><img src="{%$staticUrl%}/apps/tower/mobile/img/confirmlist/enarge_66x14_{%$data.ha_pic%}.gif" width="66" height="14" />{%$data.ha%}/100<br />
                                あと{%$data.lev_hour%}時間{%$data.lev_min%}分後に離れます</div></td>
                            </tr>
                        </table>
                        <div style="text-align:right;">
                            {%if $index==$canServceGuestId %}
                                                                 ≫<a href='{% "$baseUrl/mobile/towerfirst/firstguideseat?CF_floorid=`$floorId`&CF_ha=`$data.ha`&CF_chairid=`$data.y`&CF_guestid=`$data.tp`&CF_storeType=`$storeType`"|mixiurl %}'>案内する</a>
                            {%else%}≫案内する
                            {%/if%}
                        </div>

                        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                        <div style="background:#f39b30;text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/line.gif" width="230" height="1" /></div>
                        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                    </div><!--/.section-->
                    {%/foreach%}

                </div><!--/.inner-->
                <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
</div><!--/.content-->
        </div><!--/#waitingroom-->
        </div>
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />

</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
