{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
<div id="basebackground" style="background:#f3f3c5;">
        <div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="guide">
            <div class="content" style="background:#f3f3c5;">
                <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                    操作情報<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                </div><!--/.headline-->
                {%if !$errorHappend%}
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div class="ad_192x106" style="text-align:center;"> <img src="{%$staticUrl%}/apps/tower/mobile/img/character/v1/landlord_happy.jpg" width="150" height="120" /><br />
                    </div><!--/.ad_192x106-->
                    <div style="text-align:left;">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    うまく案内できたようじゃな。<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                        おっと、お客様の注文は受けたかい？   <br />

                    </div>
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align:center;">
                                            ≫<a href='{% "$baseUrl/mobile/towerfirst/firstgetguestonworkchair?CF_floorid=`$floorid`"|mixiurl %}'>さっそく、注文を受ける</a>≪
                    </div>
                </div><!--/.inner-->
                {%else%}
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align:center;">
                                            案内が失敗してしまいました。
                    </div>
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align:center;">
                                            ≫<a href='{% "$baseUrl/mobile/towerfirst/firstgotohome?CF_floorId=`$floorid`&CF_guide=2"|mixiurl %}'>ﾏｲ店舗へ</a>≪
                    </div>
                </div><!--/.inner-->
               {%/if%}
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
</div><!--/.content-->
        </div><!--/#guide-->
        </div>
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
