{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
<div id="basebackground" style="background:#f3f3c5;">
	<div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="guide">
            <div class="content" style="background:#f3f3c5;">
                <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                    住民委員会<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                </div><!--/.headline-->
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div class="img" style="text-align:center;"><img src="{%$staticUrl%}/apps/tower/mobile/img/character/v1/landlord_happy.jpg" width="150" height="120" /></div>
                    <div style="text-align: left;">
                    うまく注文を受けれたようだな。<br />
                    お祝いに接客ｱｲﾃﾑをﾌﾟﾚｾﾞﾝﾄしたぞ。<br />
                </div>
                    <div style=" text-align:center">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/item/0.gif" width="60" height="60"  />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                    </div>
                    <div style="text-align: left;">接客ｱｲﾃﾑを使うと、作業ｽﾋﾟｰﾄﾞを一気に「加速」できるぞ<br /></div>

                <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align:center;">
                        ≫<a href='{% "$baseUrl/mobile/towerfirst/firstspeedup?CF_floorid=`$floorId`&CF_chairid=$chairId"|mixiurl %}'>さっそく、加速してみる</a>≪
                    </div>
                </div><!--/.inner-->
                <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
			</div><!--/.content-->
        </div><!--/#guide-->
        </div>
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
