{%include file="header.phtml"%}
{%include file="header_ad.phtml"%}
<div id="container" style="font-size:x-small;">
<div id="basebackground" style="background:#f3f3c5;">
	<div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="present">
            <div class="content" style="background:#f3f3c5;">
                <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                    ﾌﾟﾚｾﾞﾝﾄ<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                </div><!--/.headline-->
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div class="section">
                        <table align="center" width="100%">
                            <tr>
                                <td width="67" align="center" style=" text-align:left; vertical-align:top;"><img src="{%$staticUrl%}/apps/tower/mobile/img/item/{%$present.id%}.gif" width="64" height="64" align="top" /></td><td style=" text-align:left; font-size:x-small;"><div style="font-size:x-small;"> [{%$time%}]<br />
                                <a href='{% "$baseUrl/mobile/tower/profile?CF_inneruid=`$fuid`"|mixiurl %}'>{%$fNickname%}</a>から、<br />
{%$present.name%}をﾌﾟﾚｾﾞﾝﾄされました<br />
								{%$present.desc%}
                               {%if $msg%} ﾒｯｾｰｼﾞ：{%$msg%}{%/if%}
                                </div></td>
                            </tr>
                        </table>
                    </div><!--/.section-->

                </div><!--/.inner-->
                <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />

<img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
<div id="userinfo">
            <div class="content" style="background:#f3f3c5;">
                <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                    {%$fNickname%}の情報
                </div><!--/.headline-->
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
					<span style="color:#f5102b;">{%emoji code="F9A0"%}Lv{%$sender.level%}</span> [経験:<span style="color:#a70f0f;">{%$sender.cexp%}</span>/{%$sender.allexp%}]<br />

                    {%emoji code="F99F"%}店舗数:{%$floorCount%}<br />
                    <div style=" text-align:right"><a href='{% "$baseUrl/mobile/towerpresent/sendgiftlist?CF_floorid=`$floorId`&CF_uid=`$fuid`&CF_msgIndex=$msgIndex"|mixiurl %}'>ﾌﾟﾚｾﾞﾝﾄする</a></div>
                </div><!--/.inner-->

		</div><!--/.content-->
        </div><!--/#userinfo-->
<img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
</div><!--/.content-->
        </div><!--/#present-->
        </div>
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br /><!--/#common-->

{%include file="common/common.phtml"%}

</div><!--/#container-->
{%include file="footer_ad.phtml"%}
{%include file="footer.phtml"%}
