{%include file="header.phtml"%}
<div id="container" style="font-size:x-small;">
<div id="basebackground" style="background:#f3f3c5;">
	<div style="background-color:#FFF;"><img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /></div>
        <div id="complete">
        {%if $step=="complete"%}
            <div class="content" style="background:#f3f3c5;">
                <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                    ﾌﾟﾚｾﾞﾝﾄ完了<br />
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                </div><!--/.headline-->
                <div class="inner">
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div style="text-align: left;">
                    {%$receiveUserName|escape%}さんに、{%$giftName%}を送りました。
                    </div>
                    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
                    <div  style="text-align:center"><br />
                                            ≫<a href='{% "$baseUrl/mobile/tower/profile?CF_inneruid=`$innerUid`"|mixiurl %}'>{%$receiveUserName|escape%}さんの店舗へ</a>≪<br />
                                            ≫<a href='{% "$baseUrl/mobile/tower/home"|mixiurl %}'>ﾏｲ店舗へ</a>≪
                    </div>
                </div><!--/.inner-->
                <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
            </div><!--/.content-->
        {%/if%}

        {%if $step=="confirm"%}
            <div id="buyitem">
                <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br /><!--/.content-->

              <div class="content" style="background:#f3f3c5;">
                  <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                      <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                  ｷﾞﾌﾄ情報<br />
                      <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                  </div><!--/.headline-->
                  <form action='{% "$baseUrl/mobile/towerpresent/sendgift"|mixiurl %}' method="post">
                      <input type="hidden" name="CF_floorid" value="{%$fid%}">
                      <input type="hidden" name="CF_step" value="nextComfirm">
                      <input type="hidden" name="CF_id" value="{%$giftId%}">
                      <input type="hidden" name="CF_name" value="{%$name%}">
                      <input type="hidden" name="CF_uid" value="{%$innerUid%}">
                      <input type="hidden" name="CF_msgIndex" value="{%$msgIndex%}">
                      <div class="inner">
                        <div  style="padding:5px 0;">
                          <div style=" text-align:center"><img src="{%$staticUrl%}/apps/tower/mobile/img/item/{%$giftId%}.gif" style="margin:3px 0;" /></div>
                          <div style="text-align:center"><img src="{%$staticUrl%}/apps/tower/mobile/img/myshop/{%if $moneyType=='g'%}goldicon_17x17.gif{%elseif $moneyType=='m'%}micon_17x17.gif{%/if%}" width="17" height="17" align="top" />{%$price%}<br />
                          <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                            ﾒｯｾｰｼﾞを入力してください<br />
                            {%if $isEmoj%}<span style="color:#f5102b;">絵文字が使えません</span><br />{%/if%}
                            <input name="message" type="text" maxlength=50 value="{%$giftMsg%}"/>
                          <br />

                          </div>
                          <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                          <div style="text-align:center"><input type="submit" value="ギフトを送る"></div>
                        </div>
                      </div>
                  </form>
                <div style="text-align:center">
                    <form action='{% "$baseUrl/mobile/towerpresent/sendgiftlist"|mixiurl %}' method="post">
                            <input type="hidden" name="CF_floorid" value="{%$fid%}">
                            <input type="hidden" name="CF_uid" value="{%$innerUid%}">
                            <input type="hidden" name="CF_name" value="{%$name%}">
                            <input type="hidden" name="CF_msgIndex" value="{%$msgIndex%}">
                            <input type="submit" value="キャンセﾙ">
                    </form>
                </div>
              </div><!--/.content-->
           </div><!--/.buyitem-->
        {%/if%}

        {%if $step=="nextComfirm"%}
        <div id="buyitem">
            <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br /><!--/.content-->

            <div class="content" style="background:#f3f3c5;">
              <div class="headline" style="background:#063d71;color:#ffffff;text-align:center;">
                  <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                                                            ｷﾞﾌﾄ情報<br />
                  <img src="{%$staticUrl%}/apps/tower/mobile/img/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
              </div><!--/.headline-->
              <div class="inner">
                <div  style="padding:5px 0;">
                  <div style=" text-align:center"><img src="{%$staticUrl%}/apps/tower/mobile/img/item/{%$gift.id%}.gif" style="margin:3px 0;" /></div>
                  <div style="text-align:left">{%$name|escape%}さんに、{%$gift.name%}を送りますか？<br />
                    {%$message%}
                    <br />
                  </div>
                  <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
                  <div style="text-align:center">
                    <form action='{% "$baseUrl/mobile/towerpresent/sendgift"|mixiurl %}' method="post">
                        <input type="hidden" name="CF_floorid" value="{%$fid%}">
                        <input type="hidden" name="CF_step" value="complete">
                        <input type="hidden" name="CF_id" value="{%$giftId%}">
                        <input type="hidden" name="CF_msg" value="{%$message%}">
                        <input type="hidden" name="CF_name" value="{%$name%}">
                        <input type="hidden" name="CF_uid" value="{%$innerUid%}">
                        <input type="hidden" name="CF_msgIndex" value="{%$msgIndex%}">
                        <input type="submit" value="確認">
                    </form>
                  </div>
                  <div style="text-align:center">
                        <form action='{% "$baseUrl/mobile/towerpresent/sendgiftlist?CF_floorid=$fid"|mixiurl %}' method="post">
                            <input type="hidden" name="CF_floorid" value="{%$fid%}">
                            <input type="hidden" name="CF_name" value="{%$name%}">
                            <input type="hidden" name="CF_uid" value="{%$innerUid%}">
                            <input type="hidden" name="CF_msgIndex" value="{%$msgIndex%}">
                            <input type="submit" value="やめる">
                        </form>
                  </div>
                </div>
              </div><!--/.inner-->
                <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="5" /><br />
            </div><!--/.content-->
            <img src="{%$staticUrl%}/apps/tower/mobile/img/deco_00_240x18.gif" width="240" height="18" />
        </div><!--/.buyitem-->
        {%/if%}
       </div><!--/#complete-->
       </div>
    <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />


{%include file="common/common.phtml"%}
</div><!--/#container-->
</div>
</div>
{%include file="footer.phtml"%}