    <div id="common" style="text-align:left;">
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
        <span style="font-size:x-small">{%emoji code="F987"%}</span><a href='{% "$baseUrl/mobile/tower"|mixiurl %}' accesskey="1">ﾊﾋﾟﾀﾜTop</a>&nbsp;
        <span style="font-size:x-small">{%emoji code="F989"%}</span><a href='{% "$baseUrl/mobile/tower/home"|mixiurl %}' accesskey="3">ﾏｲ店舗</a>&nbsp;
        {%*
        <span style="font-size:x-small">{%emoji code="F98A"%}</span><a href='{% "$baseUrl/mobile/tower/friendlist"|mixiurl %}' accesskey="4">ﾏｲﾐｸ店舗</a>&nbsp;
        <span style="font-size:x-small">{%emoji code="F98B"%}</span><a href='{% "$baseUrl/mobile/toweritem/itembox"|mixiurl %}' accesskey="5">ｱｲﾃﾑ箱</a><br />
        <span style="font-size:x-small">{%emoji code="F98C"%}</span><a href='{% "$baseUrl/mobile/towershop/shop"|mixiurl %}' accesskey="6">ｼｮｯﾌﾟ</a>&nbsp;&nbsp;&nbsp;&nbsp;
        *%}
        <a href='{% "$baseUrl/mobile/towerhelp/help"|mixiurl %}'>ﾍﾙﾌﾟ</a><br />
        <img src="{%$staticUrl%}/apps/tower/mobile/img/spacer.gif" width="1" height="3" /><br />
    </div><!--/#common-->