<div id="copyright" style="color:#999999;text-align:center;"><br />(C)Community Factory Inc.<br /><br /></div>
{%*
<div id="recommend">
	<span style="color:#ff9933">◆</span>おすすめｱﾌﾟﾘ<br />
	<span style="color:#ff9933">├</span><a href="http://ma.mixi.net/4011/?guid=ON">あしあと帳</a><br />
	<span style="color:#ff9933">├</span><a href="http://ma.mixi.net/12629/?guid=ON">みんなの時間割</a><br />
	<span style="color:#ff9933">├</span><a href="http://ma.mixi.net/9477/?guid=ON">ﾏｲﾐｸｸｲｽﾞ</a><br />
	<span style="color:#ff9933">├</span><a href="http://ma.mixi.net/9461/?guid=ON">ﾏｲﾐｸ頭脳くらべ</a><br />
	<span style="color:#ff9933">├</span><a href="http://ma.mixi.net/13651/?guid=ON">よこどりﾊﾟｲﾚｰﾂ</a><br />
	<span style="color:#ff9933">└</span><a href="http://ma.mixi.net/6230/?guid=ON">どきどきﾀﾞｲﾅﾏｲﾄﾊﾟﾆｯｸ</a><br />
</div><!--/#recommend-->
*%}