	<div id="menu">
		<div class="content" style="background:#f3f3c5;">
			<div class="inner" style="text-align:left;">
                                <!--{%emoji code="F9B8"%}<a href='{% "$baseUrl/mobile/towerservice/waitingroom?CF_floorid=`$floorId`&CF_storeType=`$storeInfo.type`"|mixiurl %}'>接客</a>:お客様にｻｰﾋﾞｽしよう!<br />-->
                                <!--{%emoji code="F9BA"%}<a href='{% "$baseUrl/mobile/towerflash/store?CF_floorid=`$floorId`&CF_isfirst=n&CF_action=pickUpMoney&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$uid`&rand=`$rand`"|mobile_flashurl %}'>集金</a>:代金・ｱｲﾃﾑを回収!<br />-->
                                {%emoji code="F9C0"%}<a href='{% "$baseUrl/mobile/toweritem/itembox"|mixiurl %}'>ｱｲﾃﾑ</a>:時間短縮やﾑｰﾄﾞの上昇!<br />
                                <!--{%emoji code="F97A"%}<a href='{% "$baseUrl/mobile/towershop/shop"|mixiurl %}'>ｼｮｯﾌﾟ</a>:便利なｱｲﾃﾑ販売中<br />-->
                                {%emoji code="F8E6"%}<a href='{% "$baseUrl/mobile/towerpresent/presenthistory?CF_read=1"|mixiurl %}'>ﾌﾟﾚｾﾞﾝﾄ</a>:ﾏｲﾐｸからのﾌﾟﾚｾﾞﾝﾄ<br />
                                {%emoji code="F9D1"%}<a href='{% "$baseUrl/mobile/towerhelp/help"|mixiurl %}'>ﾍﾙﾌﾟ</a>:困ったときはｺｺをﾁｪｯｸ!

			</div><!--/.inner-->
		</div><!--/.content-->
	</div><!--/#menu-->
