{% if $pager.maxPager > 1 %}
	<div class="pager" style="color:#006699;text-align:center;">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
    {% if $pager.pageIndex == 1 %}<span style="color:#999999;">←[*]前へ</span>{% else %}←[*]<a href='{% "$baseUrl/`$pager.requestUrl`?CF_page=`$pager.pageIndex-1``$pager.pageParam`"|mixiurl %}' accesskey="*">前へ</a>{% /if %}&nbsp;{% if $pager.maxPager == $pager.pageIndex%}<span style="color:#999999;">次へ[#]&rarr;</span>{% else %}<a href='{% "$baseUrl/`$pager.requestUrl`?CF_page=`$pager.pageIndex+1``$pager.pageParam`"|mixiurl %}' accesskey="#">次へ</a>[#]&rarr;{% /if %}<br />
	</div><!--/.pager-->
{% /if %}